### ISSUE TITLE
Is 'Add to Watch later' new additional menu really needed?

### ISSUE THREAD

**Issue by costinmx** [yuliskov/SmartTubeNext#1007]
Please consider reverting 'Add to Watch Later' additional menu from SmartTubeNext 13.31. 
This looks like a redundant setting which annoyingly increased the number of keypressing with additional steps, when you need to choose another playlist. It gets even more disturbing when you need to switch playlists for a video. 

Here's my point:
Normally, prior to this modification, accessing 'Add/Remove from playlist' (from player button or context menu) gets you directly to playlist checklist anyway - where you just have to set or remove "Watch Later" playlist - because it's always the first one on the checklist. Is just that simple, and should be enough for this setting. Is almost as short as it can be. One press for the player button and two for the context menu. 
Adding an extra "Add/Remove to watch later" now, has no major benefits as shortcut, cause its practically the same number of minimum keypresses (in player).  Instead it's making the access to other lists one more extra menus and selection away every time.
Please reconsider this. It was just fine before this change. 
Thanks

**Comment by TarkusLV** [comment]
Agreed.  Didn't understand this change at all.

**Comment by Soitora** [comment]
I've been asking for this in https://github.com/yuliskov/SmartTubeNext/issues/473 for almost a year now.

It is not redundant, for over a year the method to add to playlist was 5 keypresses:
> Long press -> Open "Add/Remove from playlist" -> Press checkmark -> Back out -> Back out

If @yuliskov is listening, please don't revert this, **2** keypresses instead of **5** is absolutely amazing

**Comment by costinmx** [comment]
@Soitora @yuliskov 

Thats (partially) true - if you just use only one playlist. The Watch later playlist. And from context menu only. But many users have lots of playlists to categorise content.  If you use more than 'Watch later' playlist, now it gets a lot more keypresses than before (at least 6 keypreses now, if counting your way!), while crusing with unnecesary redundant menus. Redunant means that you already have this feature in the menu. When you click that playlist button in videoplayer with this new menu, it's the same number of kepresses like before - except that back then you had (a +1) to additionaly pick your Watch Later playlist. Was this so hard??? +1? 

I understand your point somehow, but it's worth all this trouble this just because you had to press Back two times? Cannot be this double back issue be resolved separately ? Cause that's the only true inconvinent to the old setting. We love STN for additional features over YT app, but lately it's getting ever more clumsier and overcomplicating with redundant features. Please bear in mind there are also lots of users using multiple playlists. Also this context menu keeps geting so long that you really have to cruise a lot of clicks just to open a channel for example.

Last but not least, i bump the idea we shoud have the option to config this, so everyone gets happy.

**Comment by Soitora** [comment]
I also agree with an option, but see if from my point of view. 5 clicks got turned to 2, while yours got 1 extra added, so the average saved clicks is still 2 over the previous if you count all cases as equal.

Redundant and Shortcut  is not really the same, but yes the feature do exists, and I get why you're upset, but it has made my browsing experience a lot more fun.

Also, I barely ever use the Playlist context menu from within the Video player, when I add to Watch Later I do so from browsing outside, for example the Subscriptions feed, so that's not really an argument that works against my usecase

**Comment by costinmx** [comment]
> I also agree with an option, but see if from my point of view. 5 clicks got turned to 2, while yours got 1 extra added, so the average saved clicks is still 2 over the previous if you count all cases as equal.

"5 clicks turned 2"... because you counted those 2 "back's". Ok, but lets face it - it's was always just one 'back' needed anyway.  So, lets's say it was 4 (then) versus 2 (now), in context menu. At least one 'back' is needed to ensure the multi selection. Otherwise it could be 3 presses (then) if the dialog would have closed right after selection like it does now for WL. But a multiple playlist user would not want that, cause this is the only way you move clips from one PlayList (including WLater) to another.

Now please compare what's happening with keypresses inside the video player:
There was: "Playlist button / Select playlist (WL) / Back"  - that's 3 for WL (at least 4 for other playlists)
And now: "Playlist button / Press down / Select Playlist / Back / Back" - that's 5 for WL and at least 6 ! for other playist
Basically the +2 issue has now shifted for those who use multiple playlists. 
There was let's say +2 keypress for those with Watch List only, now there's at least(!) +2 for multiple PL users. 

This shoud be optimised to the smallest inconvenient, thats what I'm advocating for. And most likely made optional, because, I am very convinced - at some point you will also start categorising your saved videos (music, travel, live, etc). Then you will definitely see the trouble this change does. I would suggest a Mode switch setting for Watch Later user / Multiple Playlists user.  

This can also be done with account playlist detection: when your account does not have any additional playlist, stay with this mode and direct access to Watch Later. But when there are multiple playlists detected, automatically switch to previous menu behaviour.

**Comment by p1r473** [comment]
I agree with @Soitora I like the 2 clicks only
Perhaps it can be handled separately for Watch Later and then a different way for other playlists, as many people will only use Watch Later

I like less clicks for Watch Later

**Comment by p1r473** [comment]
> Or, how about switching back to old behaviour, and directly displaying all the playlists, like befiore - then, IF selecting or deselecting Watch Later (1st option), will result in immediately closing dialog (the exact number of presses you have now!). Otherwise, when selecting ANY other playlist, dialog waits for Back press to close. This will do, for everybody.

That sounds good

**Comment by Soitora** [comment]
@costinmx maybe just not include the quick Add to Watch later inside the video player? I feel that's a weird place to have that quick action

The playlist detection does not make any sense, it's not like I don't use any other playlists ever

The lmportance for me is to have the action at the Subscriptions and Home tabs, since that's when I'll mass add new videos to WL

**Comment by bartoszek** [comment]
So we agree that there should be a shortcut in the long press list view with "[add to/remove from] watch later" and "add to playlist" should work like before?

I'm have a tone of playlist, for lectures, tutorials, math, physic, security, programming, electronics, machanics etc. And use to add videos I've watched to multiple playlist form player manu after I watched them.

**Comment by costinmx** [comment]
No, what I am suggesting is that we should have globally a single function for this that brings the Checklist selection, that works differently (shortest) for Watch Later selection. I mean:

In Context Menu:
"Add/Remove Playlist / Checklist selection (instant close dialog IF first option Watch Later is selected or deselected) - that's only 2 strokes;
ELSE (press down to navigate to another playlist) 
"Add/Remove Playlist / Navigate to another playlist / Make selection / Back (to close the dialog).

That would be exactly like now for Add to Watch Later, and the shortest way for any other Playlist selection. It would also allow organising (switching on/off a video's playlist)

Player button shoud work in the same manner, bringing the Checklist selection first, acting as described above.

**Comment by Soitora** [comment]
> What I am suggesting is that we should have just **one** single function for this, that brings the Checklist selection as it used to do, but works differently (shortest) for Watch Later selection. I mean:
> 
> In Context Menu: 1."Add/Remove Playlist / Checklist selection (instant close dialog IF first option Watch Later is selecting or deselecting) - that's only 2 strokes; ELSE (press down to navigate to another playlist) Make selections / Back (to close the dialog).
> 
> For ELSE it becomes "Add/Remove Playlist / Navigate to another playlist / Make selections / Back (to close the dialog).
> 
> That would be exactly like now for Add to Watch Later, and the shortest way for any other Playlist selection. It would also allow organising (switching on/off a video's playlist)
> 
> Player button should work in the same manner, bringing the Checklist selection first, acting as described above. One single function, different behaviour if Watch Later list is checked. No additional menus.

I get your point but this doesn't sound practical, it's probably breaking a ton of guidelines and rulesets on what to do and what not to do.

Just keep function as is (now) for the out-of-video navigation (first option to quick Watch Later), then make the in-video-navigation only bring up the old playlist menu. (Why add to Watch Later inside a video already, it's not meant to be quick)

**Comment by costinmx** [comment]
> Why add to Watch Later inside a video already, it's not meant to be quick
Because it's a long video, and you want to resume later....? Sometimes, days later?

> this doesn't sound practical, it's probably breaking a ton of guidelines and rulesets on what to do and what not to do.
This simplified basic behavior "does not sound practical"? But that redundant menu is? "Breaking a ton of guidelines"? "Rulesets"? I hope there are more specific arguments on this. Cause if not, it looks more like just an ego thing, to have it your way, and not improving the product to make the best of it for all users. 

I just don't understand people that switch to STN and want it to behave EXACTLY as original YT app, often opposing to good things Yuri has bringed into this app right from the beginning. That direct acces to Playlist Checklists was one of many amazing features for eveybody. Now complicated by laziness and ego's. We now have to do 7 clicks on a function, where few months ago were only 3 necessary. Did anybody noticed how long the context menu has become on some sections? It does not fit on the screen anymore. You have to scroll. Basic "Open channel" functions through context menu, sometimes needs 5-6 clicks to reach, lately. Some functions are more and more harder to reach with every update.

@yuliskov , Yuri, I hope you take the most of this arguments and suggestions onto this subject and keep it a better optimised app.

**Comment by yuliskov** [comment]
Thanks, guys. I'm very appreciate your willingness to help. Maybe, I'll add
simplified ui mode later.

Regards, Yuriy

**Comment by Soitora** [comment]
> > Why add to Watch Later inside a video already, it's not meant to be quick
> 
> Because it's a long video, and you want to resume later....? Sometimes, days later?

My point was the quick action "Add to Watch Later", In the example you gave there's no reason why a standalone single video should require a instant-action (and not just the regular playlist selection). It is mostly only warranted in the main menu where you'll be adding up to tens of different videos each time

Your complaint is in the video overview quick select
My love for the feature is only for using it in the main menu

Our goal can align, as long as you don't want to get rid of the main menu one

**Comment by bartoszek** [comment]
I'm starting to readjust to the new behavior, but find myself often accidentally putting videos in the wrong playlist because of the last active playlist rule ¯\\\_(ツ)\_/¯

**Comment by costinmx** [comment]
Yes, I early noticed the last active playlist rule, wich also undermines the real utility of having one redundant extra menus. I didnt mention this issue from the begining on purpose, just to prove, later, the hypocrite and egocentric support for this feature by those who use only Watch Later list, or using other playlists so rarely, that they did not notice the issue.

**Comment by Soitora** [comment]
> ...the hypocrite and egocentric support for this feature by those who use only Watch Later list

Ehh, what

**Comment by bartoszek** [comment]
@costinmx ...poetisch ಥ‿ಥ

**Comment by costinmx** [comment]
@yuliskov 
OMG, Yuri, I think everybody was expecting 'Add to Watch later', as an option. 
Instead.......  Who would benefit from removal of "Add/Remove from playlist' from context menu?? 
Is not supposed to be the other way around?
