### ISSUE TITLE
Show long press menu without releasing the button

### ISSUE THREAD

**Issue by jdahdah** [yuliskov/SmartTubeNext#101]
Hey! Really enjoying SmartTube Next, thanks so much for making it. It's waaay snappier on my slow Sony Bravia than the other apps.

One little issue in the UX is that the long press menu doesn't show up until you release the OK button, no matter how long you press it. It would be more intuitive if it showed up after a set amount of time instead of having to release the button first. This is how YouTube and Smart YouTube behave and it would be great to have the same behavior here.

**Comment by adarshvadwitiya** [comment]
+1

**Comment by jdahdah** [comment]
Closing this since it has been added. Thanks!
