### ISSUE TITLE
4k 60fps lag and the frame was not smooth

### ISSUE THREAD

**Issue by 9000000** [yuliskov/SmartTubeNext#104]
The device that I use is a Sony 55x7000d TV

**Comment by foreveryoungforty** [comment]
Same here on Sony KD-65XF9005 4K.
4K videos and higher stutter on preset 4K 60fps vp9+hdr.
If I choose 4K 30fps vp9+hdr as video preset, they play smoothly.

**Comment by janowakps** [comment]
same problem, Philips 55OLED803

**Comment by klgr** [comment]
Same here Sony 70X8300F. Lot of dropped frames and it looks like it has trouble buffering. I tried changing the video buffer and the auto frame rate but it didn't make any difference

**Comment by foreveryoungforty** [comment]
See also recent issue #139  HDR Not Working

**Comment by janowakps** [comment]
with the old app (Smart YouTube TV) 4k with 60fps works smoothly so where is the difference? is this a problem with the new player?

**Comment by foreveryoungforty** [comment]
> with the old app (Smart YouTube TV) 4k with 60fps works smoothly so where is the difference? is this a problem with the new player?

Indeed , SYTV worked perfect with 4k with 60fps+hdr - the new SmartTube has issues with it ; you can read all my test results under issue 139 HDR Not working - reason why I made a cross-reference here, so I don't have to write evrything twice :-)

**Comment by janowakps** [comment]
@yuliskov What do you think about this? do you know where the bug is?

**Comment by yuliskov** [comment]
Yes, I'm aware of this bug.

Regards, Yuriy

**Comment by janowakps** [comment]
@foreveryoungforty @yuliskov I can see a big improvement in version 10.24, there are definitely fewer dropped frames

**Comment by CiNcH83** [comment]
Still the same here with 10.25. Stuttery as hell.

**Comment by yuliskov** [comment]
Appreciate your help, friends.
Still searching for the solution.
Any additional info could help.

**Comment by foreveryoungforty** [comment]
No improvement over here.

**Comment by klgr** [comment]
Can confirm last version still the same. Also noticed the text scrolling on selected video thumbnail has something like a wave pattern - I don't know if it's caused by the same frame rate issue

**Comment by foreveryoungforty** [comment]
For me the problem is solved with release 10.29 !

**Comment by CiNcH83** [comment]
It indeed drops less now. But 2160p is still flaky on a BRAVIA with quad Cortex A53 @ 1.1GHz. There is quite some micro-stuttering. I wonder whether it is possible to update ExoPlayer and enable [Tunneled Playback](https://medium.com/google-exoplayer/tunneled-video-playback-in-exoplayer-84f084a8094d) and [Async MediaCodec](https://medium.com/google-exoplayer/improved-rendering-performance-operating-mediacodec-in-asynchronous-mode-and-asynchronous-buffer-3026207850b2).

**Comment by 9000000** [comment]
solved with release 10.29. thanks

**Comment by tommysllee** [comment]
Actually there IS a workaround since earlier version..
1. Enable autoframerate
2. Disable fix fps
3. Use only the 30fps presets
4. High video buffer
5. AND FORCE SW VIDEO DECODER (because many times software is more accustomed to settings)
