### ISSUE TITLE
Disable navigation sounds

### ISSUE THREAD

**Issue by razza-guhl** [yuliskov/SmartTubeNext#1055]
Is there a way to disable the "click" sounds while navigate through the menus? (Stable ver 13.47)

I just got a fresh Fire TV stick an installed the app from scratch.  And I thought that I could disable the sound in the past(?)...

**Comment by costinmx** [comment]
Turning off 'System Sounds' in android Settings / (Display and) Sound, may do the trick...

**Comment by razza-guhl** [comment]
Thank you @costinmx. Turning off the navigation sounds in Fire TV stick generell settings, that did the trick!
