### ISSUE TITLE
[Bug] There was a problem while parsing the package

### ISSUE THREAD

**Issue by f-o** [yuliskov/SmartTubeNext#108]
I've been able to install updates through the app, via the automatic update notifier that fires when the app opens.

However, version 8.0 and 8.2, released today, gives the error listed in topic name.

Unfortunately I don't really have any more information, as (as far as I'm aware) this app does not come with an error log, like I used to attach in your other app.

I'm on Android TV 7.0, installation from unknown sources is enabled, and Google Play protect is disabled.

**Comment by kikura** [comment]
This is the same for me.

**Comment by f-o** [comment]
> This is the same for me.

I got it solved by completely uninstalling, and then doing a fresh install.
Have not had the issue since.
