### ISSUE TITLE
Android Phone Issues

### ISSUE THREAD

**Issue by BourgeoisDirk** [yuliskov/SmartTubeNext#1126]
Been using STN for my TV for a while now, works great !
Want to use it on my Android Phone now, but it appears to be missing some things ?
- Home page, scrolling the "Recommended" line of videos to the side just jumps back to the beginning constantly
- There is no side-tab or any menu option to go to settings and log-in ??
- An option in the app that directs you to change it to the default app would be convenient
- Pasting a youtube url in the search bar should just jump to the video, instead it turns up an empty search

**Comment by TTVert** [comment]
This does not work on android devices aside from fire tvs etc. unless you have a virtual mouse.  Use Vanced instead for android phones/tablets

**Comment by Loading617** [comment]
Get YouTube Vanced bro
