### ISSUE TITLE
How would you launch the app as an adb command?

### ISSUE THREAD

**Issue by aliekiddo** [yuliskov/SmartTubeNext#1136]
I'm trying to set up a remote from HomeAssistant using adb commands which I've found [here](https://gist.github.com/mcfrojd/9e6875e1db5c089b1e3ddeb7dba0f304) .

If you can launch Plex with:
am start -a android.intent.action.VIEW -n  com.plexapp.android/com.plexapp.plex.activities.SplashActivity

And the previous SmartYoutubeTV with:
am start -a android.intent.action.VIEW -n
com.liskovsoft.videomanager/com.liskovsoft.smartyoutubetv.bootstrap.BootstrapActivity

What would be the command for SmartTubeNext (beta specifically)?

**Comment by aliekiddo** [comment]
I think I've got it:
am start -a android.intent.action.VIEW -n  com.liskovsoft.smarttubetv.beta/com.liskovsoft.smartyoutubetv2.tv.ui.main.SplashActivity

**Comment by yomgui** [comment]
The following command demonstrates how to use the Android Debug Bridge (ADB) to open a specific youtube URL with an intent inside SmartTube

```
adb shell am start -a android.intent.action.VIEW -d "https://www.youtube.com/watch?v=DYpNU_3oPYk" com.liskovsoft.smarttubetv.beta
```
