### ISSUE TITLE
Add/remove from watch later playlist

### ISSUE THREAD

**Issue by muhdiboy** [yuliskov/SmartTubeNext#1158]
Hi,

this feature had been added a while ago. As of STN 13.71 Beta this isn't available anymore. There is no setting that I've found to add this to the context menu.

Although it is still possible to add videos to the watch later playlist by going through the "add/remove from playlist" menu. The individual menu entries are what are missing.

~~Something I didn't use that often but is also missing is the feature to "add/remove from playback queue". This was in the same context menu.~~ Playback queue option was unchecked in context settings.

**Comment by costinmx** [comment]
Have you just tried Settings / User Interface / Context menu ? .......

**Comment by muhdiboy** [comment]
As of STN Beta 13.77 the Context Settings contain the following options:

- Not interested
- Remove from history
- Add/Remove recent playlist
- Pin/Unpin from sidebar
- Add/Remove from playback queue
- Share link
- Select account
- Move section up
- Move section down

The playback queue option was indeed unchecked in my settings. However the Add/Remove from watch later playlist is still not available.

**Comment by costinmx** [comment]
Really?...
Add/Remove recent playlist -> Recent playlist is also Watch Later!
Did you really tried that??

**Comment by muhdiboy** [comment]
I did try that and it didn't do anything. That's why I thought the option is missing. To be sure I checked again and enabled it. Now 'Add to Watch Later' is available again.

Thank you. I think the option should be called watch later and not recent playlist. That is not a term I've ever heard.

**Comment by costinmx** [comment]
It cannot be called as you suggested because, there could be more playlists you use other than Watch Later. It's a youtube feature. 
The function is Add/Remove from **last playlist you recently used**. That playlist is mostly Watch Later, but could **also** be **other playlist** if you use more of that. 
It's not that complicated........

**Comment by muhdiboy** [comment]
Okay thanks for the explanation. That does make sense now, even though there is an extra 'Add to playlist' option.
However, because the watch later playlist is one of the main features of YouTube, this option should become its own in the context menu. That is my opinion though.
