### ISSUE TITLE
[Feature Request] : Video previews on fast forward and rewind.

### ISSUE THREAD

**Issue by M-McFly** [yuliskov/SmartTubeNext#117]
First off thanks for a great project, I really enjoy using it. Is it possible to include video previews on fast forward and rewind to make it easier to find a section of video.
I made a quick search so apologies in advance if this has already been requested.

**Comment by gate1975mlm** [comment]
+1

**Comment by gate1975mlm** [comment]
I really need feature! :)

**Comment by M-McFly** [comment]
Thanks, works well. This project is getting better and better. :-)
