### ISSUE TITLE
(Bug) Watched videos are not updated properly

### ISSUE THREAD

**Issue by gokulpoovalliyil** [yuliskov/SmartTubeNext#122]
Videos watched on SmartTube is not marked properly. Even if you watch the video till the end, on youtube site/app it shows the video as just started. Happens all the time. Since youtube thinks this is not completely watched, it will just suggest the video again.

Screenshot:
![image](https://user-images.githubusercontent.com/62756931/98672155-5ccfbd80-237b-11eb-8c03-5892933965bb.png)

**Comment by Aston97888** [comment]
Same here

**Comment by M-McFly** [comment]
Same again.

**Comment by HattabbI4** [comment]
У меня та же проблема, это сейчас единственное что мешает полностью перейти на использование этого приложения.

**Comment by gokulpoovalliyil** [comment]
> У меня та же проблема, это сейчас единственное что мешает полностью перейти на использование этого приложения.

Same here, I kinda use the original app most of the time since it's really annoying to mark these as watched later on. It would be great if they could fix this.

**Comment by jasepower** [comment]
Same. The app is great, but marking fully watched videos as only partially watched is very frustrating. I have to mark as watched on another app or thru the website.

**Comment by Aston97888** [comment]
Seems to be solved, thank you

**Comment by gokulpoovalliyil** [comment]
Issue is fixed. I verified on my tv.
