### ISSUE TITLE
Card text scroll speed setting no longer working

### ISSUE THREAD

**Issue by Maeldor** [yuliskov/SmartTubeNext#1260]
As of at least v14.04, the card text scroll speed setting is no longer working. The titles move at what feels 1x (i.e. ridiculously slow), and setting any other speed does not change it.

This was working in a recent previous version.

Nvidia Shield TV Pro 2019 - v9.0.0(33.1.0.236) (Android 11)

**Comment by y-lee** [comment]
This bug is real. It did not exist before 14.05, however.

**Comment by Maeldor** [comment]
Just updated to 14.06 and the card text scrolling speed seems to be working for me again! I'll close once definitely confirmed. Thanks for the quick fix!

**Comment by Maeldor** [comment]
Just updated to 14.06 and the card text scrolling speed seems to be working for me again! I'll close once definitely confirmed. Thanks for the quick fix!
