### ISSUE TITLE
Unable to import to AndroidStudio

### ISSUE THREAD

**Issue by han9over** [yuliskov/SmartTubeNext#13]
Hi @yuliskov ,

I'm trying to study on how you implemented the whole project (closedcaptioning in particular) and would like to debug and understand how it works in Android Studio. However, when I clone and open in Android Studio it says that _**Could not read script 'C:\Users\____\Downloads\SmartTubeNext-master\SharedModules\core_settings.gradle' as it does not exist.**_

Sorry if this is wrong place to ask, Thanks for the wonderful app.

**Comment by yuliskov** [comment]
This should work.

$ git clone https://github.com/yuliskov/SmartTubeNext.git
$ cd SmartTubeNext
$ git submodule update --init
$ gradlew buildStbetaDebug

**Comment by han9over** [comment]
Thanks @yuliskov . I was able to open it up and when I hit run in AndroidStudio, getting below error. Any suggestions?

Could not find com.zlc.glide:webpdecoder:2.0.4.9.0.
Searched in the following locations:
  - file:/D:/Android/Sdk/extras/m2repository/com/zlc/glide/webpdecoder/2.0.4.9.0/webpdecoder-2.0.4.9.0.pom
  - file:/D:/Android/Sdk/extras/m2repository/com/zlc/glide/webpdecoder/2.0.4.9.0/webpdecoder-2.0.4.9.0.jar
  - file:/D:/Android/Sdk/extras/google/m2repository/com/zlc/glide/webpdecoder/2.0.4.9.0/webpdecoder-2.0.4.9.0.pom
  - file:/D:/Android/Sdk/extras/google/m2repository/com/zlc/glide/webpdecoder/2.0.4.9.0/webpdecoder-2.0.4.9.0.jar
  - file:/D:/Android/Sdk/extras/android/m2repository/com/zlc/glide/webpdecoder/2.0.4.9.0/webpdecoder-2.0.4.9.0.pom
  - file:/D:/Android/Sdk/extras/android/m2repository/com/zlc/glide/webpdecoder/2.0.4.9.0/webpdecoder-2.0.4.9.0.jar
  - https://dl.google.com/dl/android/maven2/com/zlc/glide/webpdecoder/2.0.4.9.0/webpdecoder-2.0.4.9.0.pom
  - https://dl.google.com/dl/android/maven2/com/zlc/glide/webpdecoder/2.0.4.9.0/webpdecoder-2.0.4.9.0.jar
  - https://repo.maven.apache.org/maven2/com/zlc/glide/webpdecoder/2.0.4.9.0/webpdecoder-2.0.4.9.0.pom
  - https://repo.maven.apache.org/maven2/com/zlc/glide/webpdecoder/2.0.4.9.0/webpdecoder-2.0.4.9.0.jar
  - https://jcenter.bintray.com/com/zlc/glide/webpdecoder/2.0.4.9.0/webpdecoder-2.0.4.9.0.pom
  - https://jcenter.bintray.com/com/zlc/glide/webpdecoder/2.0.4.9.0/webpdecoder-2.0.4.9.0.jar
Required by:
    project :smarttubetv

**Comment by han9over** [comment]
Nevermind. I was able to figure out.
