### ISSUE TITLE
[Question] Can we override the YOUTUBE button on the Chromecast for Google TV remote ?

### ISSUE THREAD

**Issue by Fangh** [yuliskov/SmartTubeNext#1309]
Can we override the YOUTUBE button on the Chromecast for Google TV remote ?

When I click this button on the remote it opens youtube. can it opens SmartTube ?

**Comment by stevensmedia** [comment]
Best best would be an app like Button Mapper.

**Comment by Fangh** [comment]
I used Button Mapper and it worked great. thank you.
