### ISSUE TITLE
Some videos cannot be played on beta 9.3

### ISSUE THREAD

**Issue by LDA-VN** [yuliskov/SmartTubeNext#131]
Lots of videos can't be played, I tried on Sony ATV and Mibox S they couldn't play either.  I am using the latest Smarttube next beta 9.3.  With Google's Youtube, all of the above videos play well.  For example : https://youtu.be/O9W4lpwPaVk

**Comment by buthig666** [comment]
At the time of this complaint Youtube has been globally having issues on the server side.  the app works fine

**Comment by LDA-VN** [comment]
But why can I still watch that video on youtube Google without a problem.

**Comment by LDA-VN** [comment]
Smart Youtube and SmartTube Next both share the same problem. Youtube is doing very well.

**Comment by buthig666** [comment]
Its working fine for me.  I'm in australia.  They may not have fixed it across all platforms and regions yet.  I would at least try restarting you TV.  I can't help you past that.  I am just here to give feedback to help with the beta process.  I don't know anything about the underpinnings of the app.

**Comment by LDA-VN** [comment]
I don't understand why after updating to 9.3. I have tried it on both Sony ATV 8.0 and Mibox S 9.0 devices. Both devices have the error. I am living in Vietnam. Not every day, until today, after updating to 9.3. I tried rebooting the device and clearing the cache both failed. Not all videos have this error.

**Comment by LDA-VN** [comment]
I will try to install the lower version again. Because Youtube Google doesn't have that problem: ((So can't say it has server problem.

**Comment by buthig666** [comment]
Just be patient for a couple of hours, like I said you tube is having issues today globally.

**Comment by LDA-VN** [comment]
I tried it on SmartTube Next beta 7.0 also failed. Here's my problem :(. I should wait as you say.
https://youtu.be/-hOHUGc6GfU

**Comment by LDA-VN** [comment]
It has been working on the latest SmartTube Next beta 9.6 :)). 9.3 beta or less Some videos don't work.
