### ISSUE TITLE
Can’t add account info

### ISSUE THREAD

**Issue by Aspie64** [yuliskov/SmartTubeNext#1315]
When I go to Accounts, Sign In, on Nvidia Shield, there’s just a QR code. Is there any way to manually type in account details?

**Comment by jasonding121205** [comment]
same problem with my shield tv

**Comment by Aspie64** [comment]
Sign in to YouTube on your phone/tablet while on the same network and scan the qr code with that. Pretty long-winded if you have multiple accounts, would be so much easier to just log in via the app.

**Comment by jasonding121205** [comment]
windows browser solved the problem.tks!
