### ISSUE TITLE
Playback interrupted with error : Video source is not working or Incorrect time

### ISSUE THREAD

**Issue by LeCommonMan** [yuliskov/SmartTubeNext#1331]
**"Video source is not working or Incorrect time"**
Stated to get this error past 2-3 days, during placyback, mostly on videos which has duration of over 20 minutes.
The only way to continue that video playback is - exit playback and start it again.
Changing buffer size or lowering down resolution to even 480p doesn't solve this.

Please note starting the video playback at the very beginning has no issues. playback is interrupted only in middle. 

Device: FireTV stick.

**Comment by SanteriHetekivi** [comment]
I get this same error on my Nvidia SHIELD Android TV P2897 running Shield Experience 9.0.1 (Android 11), but for me some videos do not start just loop loading spinner and **Video source is not working or Incorrect time error**.

Official Youtube app works fine.

**Comment by abigchopstick** [comment]
I have the same issue for every video, browsing is fine though, only video playback, checked timing on AndriodTV is fine too.

Device: xiaomi TV4
