### ISSUE TITLE
Home screen channels 

### ISSUE THREAD

**Issue by aaref1234** [yuliskov/SmartTubeNext#1347]
I installed the app on Android 8, but the app does not appear in the list of “Home screen channels” as well as the list of “Play Next” 

But it works without problems on Android 9
 
It also works on Android 8, but an old version of the app .

**Comment by aaref1234** [comment]
I can't chose recommend because the app is not in the list .

**Comment by yuliskov** [comment]
Guys, could you remember the latest working version?

**Comment by amaczuga** [comment]
> the latest working version?

I'm afraid I didn't note it down, yet my request was pretty imminent after the update, so around the time of the comment...

**Comment by aaref1234** [comment]
![MergedImages.jpg](https://user-images.githubusercontent.com/62560435/178467904-7343b124-e7f4-4cfa-8950-1e533242fc31.jpg)

**Comment by aaref1234** [comment]
![Screenshot_20220712-121040.png](https://user-images.githubusercontent.com/62560435/178468025-f94da4bb-343d-41d9-9ba5-58cf78f8fe7c.png)

**Comment by amaczuga** [comment]
> Guys, could you remember the latest working version?

Unfortunately, no. It stopped working a while before the issue OP. 

Previously smart tube option was present in Settings/Home screen/Recommendations row, but there were no recommendations displayed on home screen.
Now, the option to enable recommendations from SmartTubeNext is no longer there. Gone. 
AndroidTV 8

please help...

**Comment by amaczuga** [comment]
ok, upgraded to 16.70 and it works now! thank you!!! :  )

**Comment by aaref1234** [comment]
I tried it and the problem is not resolved .
And I forced turn off the Android Home TV and cleared the cache as well .
