### ISSUE TITLE
[Feature Request] Shuffle for playlists PLEASE!

### ISSUE THREAD

**Issue by ItzWilliee** [yuliskov/SmartTubeNext#1348]
I love this app, great job yall! What I would love to see is shuffle for playlists. I would love to be able to listen to my music on shuffle because when playing a playlist and having it go in the same order makes songs kinda lose their funk, like King Kunta is a great song but say if it's always number 3 on a playlist then it's just the same old same old

**Comment by Tilgor** [comment]
+1

**Comment by emacrack** [comment]
+2

**Comment by sokai** [comment]
dup #924
@ItzWilliee plz close this issue #thx

**Comment by RomanCastroG** [comment]
> I love this app, great job yall! What I would love to see is shuffle for playlists. I would love to be able to listen to my music on shuffle because when playing a playlist and having it go in the same order makes songs kinda lose their funk, like King Kunta is a great song but say if it's always number 3 on a playlist then it's just the same old same old

exactly! "these hoes ain't loyal" doesn't hit the same when is always number one on the playlist 😔

**Comment by jjjheating** [comment]
Still no shuffle songs from one playlist.
