### ISSUE TITLE
Shield HDR Not Loading

### ISSUE THREAD

**Issue by EdmundChaplin** [yuliskov/SmartTubeNext#1359]
Whenever an HDR format is selected, the video will not load and continue to refresh in a loop.

**Comment by retorquere** [comment]
Same here

**Comment by finnzz** [comment]
YouTube HDR is in VP9 profile 2.  The Shield doesn't support that codec, so no HDR in YouTube on the Shield.

**Comment by retorquere** [comment]
I didn't get a chance to select anything

**Comment by finnzz** [comment]
Maybe try toggling 'skip codec level profile check'

Setting / video player / developer options

**Comment by EdmundChaplin** [comment]
> YouTube HDR is in VP9 profile 2. The Shield doesn't support that codec.

I see, thank you
