### ISSUE TITLE
Sound is distorted

### ISSUE THREAD

**Issue by PashaGeronimo** [yuliskov/SmartTubeNext#1416]
There is a problem - the sound is distorted. On Xiaomi MI TVs. Apparently the sound gain in the application is turned to the maximum. When checking, in the original youtube application - the same video is not distorted. And the sound is noticeably quieter.
Is it possible to display in the application a separate adjustment of the sound gain or the volume of the application itself?

Thank you.

**Comment by PashaGeronimo** [comment]
fixed

**Comment by smartyn13r** [comment]
Same issue with Xiaomi X Pro 2025 TV 
Distorted Sound when playing any video using latest version of SmartTube but same video play good sound on regular YouTube
