### ISSUE TITLE
Videos skipping ahead

### ISSUE THREAD

**Issue by koffeedude** [yuliskov/SmartTubeNext#1437]
Some videos are not starting at the beginning when you begin them they are skipping 2 minutes into the video. Others start at beginning but most are starting at least 2 minutes in. I cannot find a setting to fix this issue.

**Comment by jaytea33** [comment]
Having the same issue. It's super frustrating

**Comment by rramirezg22** [comment]
same problem here

**Comment by koffeedude** [comment]
_Update:_ It has been over 2 weeks and this problem is still happening. In fact I think it got worst. Some longer videos start almost at the end with maybe a minute left. I have to rewind the video to the beginning. I can't figure out what is causing this. I am using the stable version 14.60 and keep checking for an updated version which I really hope fixes this problem.

**Comment by koffeedude** [comment]
Version 14.82 update solved this problem!
