### ISSUE TITLE
ability to creat new playlist  

### ISSUE THREAD

**Issue by MD77MD** [yuliskov/SmartTubeNext#1444]
alot of times i find myself wanting to add a video to a  playlist..  currently i can only add videos to preexisting playlist which is great

however most of the times the preexisting playlists are not relevant, at the same time i can not creat a new playlist... so i end up having to go find my phone and creat a new playlist from there, then go back to the tv to add the video(s) to newly created playlist... 

as you can see this is much of hassle... i which if we could  have the ability to just create playlists from the playlists menu 

video ==> add video to playlist ==> playlists menu ==> creat playlist ==> name playlist ==> save ==> finish adding video.

**Comment by github-monkey** [comment]
The SmartTubeNext interface shows two methods to create a new playlist -- by long-pressing on a video before it plays or long-pressing on the Playlists section.

Neither work for me.

If creating playlists is impossible on Android TV, please remove the option from the interface for now.

**Comment by costinmx** [comment]
Just a comment, as an experienced youtube user: 
I would definitely keep away from managing playlists outside YT web interface. It has evolved in quite sensitive matter, it also implies so may different functions beside basic Add/Remove... I mean like setting visibility/privacy, hidden videos, individual arranging, description, setting list image, adding new videos to top or bottom, etc
Not to mention what a possible catastrophe would be accidentaly deleting a large playlist... 
Glad to see this is an option in STN. Hope all the playlist functions will keep staying optional from the context menu.

**Comment by sgon00** [comment]
I found two UIs to create a new playlist in SmartTubeNext. But none of them works.

**Comment by MD77MD** [comment]
this feature has been added
