### ISSUE TITLE
MrBeast Video in some random language I can't understand

### ISSUE THREAD

**Issue by Xitee1** [yuliskov/SmartTubeNext#1448]
For some reason when I watch a MrBeast Video it isn't in English but in some other language. On my phone the same Video is in english as normal. I haven't seen this on any other channel than MrBeast.
https://user-images.githubusercontent.com/59659167/164322806-6d9125d0-c2e1-437c-be4e-adbf3294f3e8.mp4

Also, why is there a newer version available than even the Beta? I have updated to 14.62, but that version doesn't exists in the releases??

**Comment by Burgercat** [comment]
You can select the audio language under playback settings then audio formats.

**Comment by socalbosoxgal** [comment]
I am having the same issues with Mr. Beast videos. I'm a newbie. Where are the playback settings?

> You can select the audio language under playback settings then audio formats.

**Comment by socalbosoxgal** [comment]
@Burgercat which settings did you change to fix the Mr. Beast videos?

**Comment by Xitee1** [comment]
> @Burgercat nevermind, I found it! So you have to go into a Mr. Beast video from SmartTube. Then within the video player, click HQ (Quality Settings) and then Audio Format and look for EN,MP4A. That fixes it for all of them afterward.

Wow thanks, I actually have had that problem again not too long ago but this time I could not find that option anymore, I've searched for more than 10 minutes in the settings. And it's actually so simple.

**Comment by joewebdev** [comment]
This is still happening on Android TV (Google TV, whatever you wanna call it). Also, there is no "en, mp4a" in the audio format menu, as suggested by @socalbosoxgal

**Comment by socalbosoxgal** [comment]
Hi! I went into Smartube today. My videos are playing in English, but the Audio Formats options have indeed changed. There are no language settings in there anymore. My current setting is 0.39 Mbps, mp4a, 5.1. But prior to this update, I had it set to the en option. Somehow it appears to be maintaining the English settings.

**Comment by socalbosoxgal** [comment]
Also, you may want to post your issue on the Telegram group. That is how I got  help on my issue when it originally popped up. Another user somewhere helped me with it. I downloaded telegram and searched for Smartube.
