### ISSUE TITLE
Pressing "Back" triggers PiP; option to disable gone

### ISSUE THREAD

**Issue by Tailszefox** [yuliskov/SmartTubeNext#1468]
Hi. I have STN set up with "Background playback" set to "Only audio". This way I can turn off my screen and still have the video playing.

I also had the PiP activation key set to "HOME". So if I pressed Back when watching a video, the video would stop.

After updating to 14.68, now whenever I press Back, PiP engages and the video continues playing in the background, instead of stopping. Even worse, if I start a different video, that video keeps playing in the background and I have to press the PiP button at the top to bring it back fullscreen.

I tried to look for the PiP activation setting, thinking it had been reset, but it seems to have been commented out with commit 31ef9971df8c7410c3f527200cd1c8e87d84e983 and is thus not available.

Would it be possible to bring back that option to get the old behavior, please? The new behavior is pretty inconvenient at the moment. Since you asked for feedback in the changelog I figured I should make my problem known.

**Comment by costinmx** [comment]
> Even worse, if I start a different video, that video keeps playing in the background and I have to press the PiP button at the top to bring it back fullscreen.

This must be related to the second part of my complaining here #1465 
Selecting another video is not automatically bringing back the fullscreen anymore. 
I really don't understand why to disallow 'back' key from stoping the video. There is no other way to stop the video from playing, if your  sistem/remote does not have playback keys (i.e. CC w Googe TV does not)

> Would it be possible to bring back that option to get the old behavior, please? The new behavior is pretty inconvenient at the moment. Since you asked for feedback in the changelog

I also subscribe to that. Or make it optional, perhaps ?

**Comment by Tailszefox** [comment]
Just installed and tried 14.69; the Back button now works like before and the video goes full screen when starting a new one. Thank you very much for the quick fix!
