### ISSUE TITLE
Videos being added to queue automatically despite auto-play turned off in settings

### ISSUE THREAD

**Issue by TGBDalton** [yuliskov/SmartTubeNext#1476]
As the title says, after the latest update on my Fire Stick, videos are automatically being added to the watch queue when the list of chosen videos end. I've checked in  STN's settings, Vanced settings, the normal YouTube app settings, YouTube web settings and everywhere else I can think of and "Auto-play" is turned off across the board.

Please see the attached video; hopefully you can fix this or tell me what I'm doing wrong as it's driving me nuts!

https://user-images.githubusercontent.com/104701833/166127364-b283b354-95f7-4778-96f6-3a9797cc0d14.mp4

**Comment by Christopher-Peterson** [comment]
I've also had this problem after the recent Fire Stick 4K update. Autoplay is also disabled on Vanced.

**Comment by akamichoff192** [comment]
To add on, I have also been experiencing this issue, but with my installation being directly on my television (Sony). Using a remote and selecting a video on the home page works as expected, I have SmartTube set to only continuously play playlist videos, and it respects that setting, stopping after the video.

When I connect a phone and use it as a remote, adding videos into a queue, it plays through those normally until it reaches the end. Then it seems to grab whatever video would be auto-played, adds it to the queue, and then plays that.

I similarly do not have autoplay enabled anywhere.

**Comment by TGBDalton** [comment]
Issue seems to have been fixed a while back, I just forgot to close it until now

**Comment by Abz321** [comment]
> while

How did you fix this situation because mine still sends videos too the playback queueand am constantly having to click off the video and removing them

**Comment by hitchcme** [comment]
I keep setting up a fairly long play queue, and then it always resorts to playing endless LegalEagle videos instead, always when I'm in the middle of doing something else.  It used to be MSNBC or John Oliver videos.

Considering what this excellent creation is intended to combat, as I understand it; could it be that youtube is intentionally modifying the queue to
1) maintain a political ideology and the position and width of the Overton window, all under the guise of de-radicalization.
  1a) too far left => watch these recommended Centrist through Far right videos.
  1b) too far right => here's some recommended  Centrist through "BreadTube" videos.

Or (not "exclusive or" (XOR), just simple and inclusive "or")

2) sabotage to perpetuate profit from Premium Subscribers; Something about Malcolm X's poetic words on Palestine.

Also, would it be possible to maintain a locally managed queue that can act kind of like rsync, and favor the local "master" queue, or maybe even have the option of completely bypassing YouTube's builtin queue functionality altogether?

I imagine playlist and queue information is all built on JSON strings, and I suppose an unreceived file or array of json data could possibly be treated as just an empty queue or an empty playlist to then resort to suggested videos.
