### ISSUE TITLE
App very slow to load then videos not playing

### ISSUE THREAD

**Issue by pyschometal** [yuliskov/SmartTubeNext#1482]
App is very slow to load (1 min- 3 mins ), black screenwith loading circle. 

When video previews do show, they don't play at all. Tried both stable and beta versions.  I tried clearing cache and data, then I also tried uninstalling and re-installing.

**Comment by Mengkzhaoyun** [comment]
the same problem

**Comment by WildSeeds** [comment]
Had the same problem for two days

**Comment by pyschometal** [comment]
Seems to be working now. There was definately a issue as I had it on multiple devices. Thanks for the fix :-)
