### ISSUE TITLE
Feature Request: Turn off animated thumbnails

### ISSUE THREAD

**Issue by mhawkins30** [yuliskov/SmartTubeNext#15]
Great project, I appreciate how much faster and more responsive it is than Smart Youtube TV.

In addition to other features I've seen brought up on this page, I'd like to have the ability to turn off the animated thumbnails that show up when you have a video thumbnail highlighted, because I find them distracting.

Thank you!

**Comment by steve51184** [comment]
I hope this'll be an option in settings if they implement a settings page
