### ISSUE TITLE
App stopped working yesterday, can't access account-related content anymore

### ISSUE THREAD

**Issue by cablehub** [yuliskov/SmartTubeNext#1564]
The app worked great until yesterday, I can now no longer access my _channels_, _subscriptions_, _history_ and _playlists_.

I can still sign in fine, but none of the items mentioned above work. _Channels_ just displays a black empty screen, _Subscriptions_ displays 'can't load content', _History_ displays 'can't load content', _Playlists_ displays three playlists with empty grey boxes where the icons used to be.

I tried signing out and signing back in, reinstalling the app and using the latest beta instead of the latest stable version of _SmartTubeNext_ - no change.

My device is an NVIDIA Shield TV Pro 2019 with the latest official unmodified firmware.

**Please help :)**

**Comment by nicot38** [comment]
I have the same problem on NVIDIA Shield TV 2015

**Comment by kitor** [comment]
Similar story, in my case channels won't load (black screen), subscriptions show login button.  Music, history and playlists works.

**Comment by totaldecay78** [comment]
Same issue here except the history still displays.
Using latest version on Fire stick 4K, fire stick basic and Panasonic android tv (10)

**Comment by pewter77** [comment]
Maybe related, I can't login in a new install.

**Comment by K2UGA** [comment]
Same here, bit good news is that Yuli is on it. See this thread. https://github.com/yuliskov/SmartTubeNext/issues/851#issuecomment-1137787422

**Comment by cablehub** [comment]
> Same here, but good news is that Yuriy is on it. See this thread. [#851 (comment)](https://github.com/yuliskov/SmartTubeNext/issues/851#issuecomment-1137787422)

Thank you, that is good to know! The user [jacklroberts](https://github.com/jacklroberts) reported the issue in that thread two days ago, so it would seem that this is indeed the same problem.

**Comment by cablehub** [comment]
The latest beta fixes _channels_ and _subscriptions_ for me, although _history_ and _playlists_ still don't work.

Not sure why this is though, as the release text states:
`Bug with broken subscriptions isn't fixed yet. Sorry.`

??

**Comment by orosalsero1** [comment]
I'm having same issue, installed the new stable version SmartTubeNext and I'm unable to login to my YouTube account, so I have no access to my subscribed channels.

**Comment by cablehub** [comment]
Forgot to close this, the issue was solved for me with the update that was released a few days after May 28th.
