### ISSUE TITLE
Clock and date to US Style "12hr/mm.dd,yy"

### ISSUE THREAD

**Issue by costinmx** [yuliskov/SmartTubeNext#1649]
~~Cards on some clips (without special still card set - try Reuters for example), have a thick black border around the image. This is happening **only** on STN and STN Beta. YT web, app or other apps are fine. v15.05 fixed the card animation, but the thumbnail thick black border is still there.~~  Solved

Also, just since v15.05 update, STN Beta clock has permanently changed to 12hr setup, permanently displaying that annoying AM/PM indication both on main screen and also on player. My app and regional country settings are all set for 24hrs clock. There is no other app in my TV that shows 12hr clock. Only STN, since v15.05. @yuliskov, please please revert this setting at least how it was before this update, or make it an optional setting. #1639 
Update: Looks like an Country setting work in progress, Country setting is changing time/date behaviour.

**Comment by joachimtingvold** [comment]
The change happened before 15.05; I'm on 14.99, and it's 12h only there as well. I believe I was on some other 14.9x-release prior to upgrading to 14.99, where I had 24h clock.

**Comment by costinmx** [comment]
Strange enough, for me only it's an issue only from 15.05. I also use 14.99 STN Stable, it shows 24hr clock. 
v15.06 did not fixed this

**Comment by joachimtingvold** [comment]
I'm on the beta track, so not sure if 14.99 beta and 14.99 stable is different?

**Comment by yuliskov** [comment]
14.99 beta and 14.99 stable are the same. No diffrence at all.

**Comment by joachimtingvold** [comment]
OK, then the problem is also on 14.99. I have not yet upgraded to 15.x.

**Comment by costinmx** [comment]
Agree, both 14.99 (stable and beta) worked fine for me regarding the time/date issue.

**Comment by joachimtingvold** [comment]
Then there are other factors in play, because I see it on my 14.99 installation on my Shield. Prior to upgrading to 14.99, I had 24h clock. No other changes or upgrades were done. Unfortunately I cannot recall the previous version I was on, but I had recently upgraded, so it can't have been many versions in-between.

**Comment by costinmx** [comment]
I'm on Android TV, also on Google TV (2 separate devices). 14.99 works fine, 15.05 (or 06) has this issue

**Comment by joachimtingvold** [comment]
Well, I still see it on 14.99 (-:

Looking at the commit logs, the were lots of changes introduced between 14.90 and 14.96 regarding the clock, so it was probably introduced as part of those changes. Why you have it working on 14.99 I cannot explain, but I guess @yuliskov  will figure it out eventually.

**Comment by costinmx** [comment]
Looking at v14.60, cards black border it was not an issue.

**Comment by costinmx** [comment]
First, looks like missing recommended channel from ATV Home screen, has something to do with recently inserted **Advertising** clips on first position of STN Home tab. Now, this **Ad** does not appear into original YT app Home tab, which makes it very questionable. Is it an STN "feature"?

Second, I want to express my full **disappoinment** to new 'cosmetic' updates while more and more heavy bugs are turning into a second wave of permanent issues. Somwhere around v14.60 everything worked and looked perfect. It's all downhill from there, and looks like it's getting worse...

**Comment by yuliskov** [comment]
@costinmx please post the screens with the second issue. I have some assumtion about the source of the issue.

**Comment by costinmx** [comment]
Here are the screenshots for all these issues. For comparison, RED Theme = Stable v14.60, GREEN Theme = Beta v15.10
You may also notice a new issue. Cilps in Subscriptions do not refresh as fast in newest Beta v15.10 as they did in v14.60. There's at least half hour delay, maybe more. In 'Channels' they are live updated as they publish, but in 'Subscriptions' there is a significant delay.

First, the black border issue since v15.x (green theme). Compare it to v14.60 (red theme)

![Screenshot_20220702-035206](https://user-images.githubusercontent.com/74626232/176981156-aa238c07-ff06-4888-92f0-3fb24f265851.png)

![Screenshot_20220702-035241](https://user-images.githubusercontent.com/74626232/176981162-9bf84217-f8a0-4f6a-bdad-253e55f3211e.png)

Next, 12 hour issue 'month-day,year' date since v15.x, also in player time display.  
In my v14.99 was a regular 24h clock, 'day-month-year' date.
Also you may notice the new delay in Subscriptions (captures were made in immediate sequence,). Two newer clips are missing from Beta v15.10.

![Screenshot_20220702-035951](https://user-images.githubusercontent.com/74626232/176981387-6dccd934-81c9-4cee-bbab-76f655a163f3.png)

![Screenshot_20220702-035330](https://user-images.githubusercontent.com/74626232/176981295-1ae0d531-c3f6-47ff-9039-bd31c049e266.png)

![Screenshot_20220702-035336](https://user-images.githubusercontent.com/74626232/176981370-0d3db193-dffb-438a-9a3c-b8e73b57fddd.png)

Finally, the black border issue as seen from ATV Home launcher. Stable v14.6 in red and Beta v15.1 in green comparison:

![Screenshot_20220702-033945](https://user-images.githubusercontent.com/74626232/176981565-8f737d9a-ff35-4abb-9928-a60bca87ebc7.png)

**Comment by costinmx** [comment]
Subscriptions issue update: It is not a delay, some channels are not showing anymore: Reuters, Tennis TV, Comedy Central UK, etc

**Comment by costinmx** [comment]
Regarding Cards black border: @yuliskov please look at those three cards comparison (v14.60 vs v14.96), and you will see exactly where the problem comes from: 

![Screenshot_20220702-144918](https://user-images.githubusercontent.com/74626232/176999828-737e9ff3-dae9-4415-897f-e5c64b473e65.png)
![Screenshot_20220702-144924](https://user-images.githubusercontent.com/74626232/176999832-1d6104ce-1ca4-428a-8276-3a489fedde08.png)
