### ISSUE TITLE
Home Recommendations limited to 5 items

### ISSUE THREAD

**Issue by bigshiny90** [yuliskov/SmartTubeNext#1658]
Latest release from today Beta 15.09

suddenly on the Home Channel, all sections - specifically Recommended - are limited to 5 items.

**Comment by Ep0chalypse** [comment]
Still happening to me on Beta 5.10. 

All rows are limited to 5.

**Comment by bigshiny90** [comment]
just tested 15.10, same issue.

**Comment by bigshiny90** [comment]
Fixed in 15.11
