### ISSUE TITLE
v15.2x More new features - more known bugs are completely ignored

### ISSUE THREAD

**Issue by costinmx** [yuliskov/SmartTubeNext#1674]
@yuliskov - Don't take this wrong - The last two months of updates are a complete mess in terms of bugs.
There is nothing stable anymore, well known usual features are dissapearing even in Stable versions. V14.99 was promoted as bugged in description(!). Every update has become a recipe to new problems, and a race for a downgrade regression in user side. 

Let me just mention one example: When you added this small feature, almost useless, 'Country' button in v15.x, you took out the entire time/date SmartTube system by forcing it to US style (showing am/pm time, and month-day reversed date). Previously this behaviour was succesfully controlled by OS system settings. Not anymore. Same story goes for recalibrating cards image to fit 'shorts', and so on many many issye. Very small improvements came with harder issues.

Latest updates are the most buggied versions so far, since the start of the development of SmartTube Next 2 years ago. Wherever you look into the app, there is an issue. I am forced to still using v14.60, because everything is still working fine here - a BLISS compared to new heavy bugged v15.x. I would name it **SmartTube Last (v14.60)**

I am considering ceasing my contribution by stop reporting bugs for this app. It's not that easy to volunteer and find time to capture and write down reports of these issues. I really hoped you would apreciate this user effort more. Now, it looks like a complete waste of time.  It has become obvious the development shows less and less interest in fixing the unusual high number of current issues (#1504 #1649 and many more others) in favor of arguable useful new features. It's becoming obvious you don't really value user feedback reporting, any more. This also made me reconsider several times a possible financial contribution to this amazing project you started. You should be aware that some users are affording YT Premium but we are preffering playing with STube because of the really useful features you bring from the start of this project.

**Comment by yuliskov** [comment]
@costinmx I'm very sorry that I've disappointed you. The main problem here is a github issue system. I've found it very inconvenient because it takes too much time to communicate with the user. Pleasee understand me, I'm trying to fix the bugs that cannot be reproduced on my setup, so the fast communication is vital. Currently, I perefer live chating via Telegram. If you're willing to fix all described bugs, please contact with me via Telegram. My account (github users): t.me/yurok9711 or via group (regular user) t.me/SmartTubeNext_EN

**Comment by costinmx** [comment]
Ok, I understand, and will try to install Telegram on my phone (is not usual in my area), and get back to you.
I really appreciate your effort, it's just very frustrating to loose some of the STN features you are used to from the start.

**Comment by yuliskov** [comment]
@costinmx cards black borders bug seems fixed. Now, I need you to test the build. Contact with me via t.me/yurok9711
