### ISSUE TITLE
Regular SEARCH not working on Nvidia Shield

### ISSUE THREAD

**Issue by ZandigSlaytanic** [yuliskov/SmartTubeNext#1708]
Updated to 15.47, and noticed the same on the previous version...

Search is no longer working.
It appears to default to 'Instant Voice Search' (which I don't use) even though I have that turned off in the settings.

When you do a search it just spins attempting to load the search results, which it never does.

**Comment by h3rm** [comment]
same problem on fire tv stick 4k max

**Comment by another2020githubuser** [comment]
Another firestick 4k user.  No search results for about the last 24 hours.

**Comment by ZandigSlaytanic** [comment]
Fixed in 15.50
Thank you.
