### ISSUE TITLE
No video will play on smarttube on firestick when signed in to youtube account

### ISSUE THREAD

**Issue by mrnot81** [yuliskov/SmartTubeNext#1760]
No video playing on firestick.  The video plays but you see no picture or sound and just see the progress bar moving forward.  There is also no video formats listed when playing the video. 
All works fine when I haven't signed in using an account.  Once I sign in using my youtube account I see this issue.  I can see that youtube has access under my google account under "Google apps - These are trusted apps by Google you installed on your devices. Remove any that you no longer use"
I tried reinstalling the previous stable release but the same issue..tried resetting my firestick back to factory defaults and reinstalled but same issue again.
Doesn't look like a bug with smarttube but I'm unsure what I have to do to fix this so I can see my history, watchlist etc.

**Comment by koffeedude** [comment]
I have the same issue on my firecube. I cannot use the app while I am logged into my account! I have tried everything as well to get it to work but no success so I gave up on it and watched my subscriptions on ytube on my PC. So frustrating!

**Comment by SexyNick** [comment]
This just started happening to me today. When logged in, the occasional video will play but not without constant buffering to the point it's unwatchable. Lowering the resolution seemed to work but it would have to be cranked way down to work.

**Comment by elle8che** [comment]
Sorry, I may have replicated this issue on #1765

**Comment by mrnot81** [comment]
I've just updated to 15.78 and that has fixed the issue it would seem.  Thanks to the development team.

**Comment by UZOgithub** [comment]
With the new update (15.78 smarttube stable) I can't start any video on my FireTVstick (Tank)!!!

Every time I start a video the mainscreen appears.

edit: It seems the problem is only when I am logged in with my youtube account. Without account it works.
