### ISSUE TITLE
Fixed: Thanks yuliskov!! 

### ISSUE THREAD

**Issue by thestuartcarson** [yuliskov/SmartTubeNext#1766]
New update fixes the playback issue! I know this technically not a new “issue” but I just wanted to create this to thank the dev(s)! SmartTube Next is the best thing ever. Absolute Legend(s)!

**Comment by travelingbear** [comment]
Thanks yuliskov

**Comment by ChaliKaki** [comment]
yes very great thank you...seems ok now😁😁😁

**Comment by UZOgithub** [comment]
With the new update (15.78 smarttube stable) I can't start any video on my FireTVstick (Tank)!!!

Every time I start a video the mainscreen appears.

**Comment by JJo1118** [comment]
Thanks yuliskov!!!  Fixed the issue for me.

**Comment by elle8che** [comment]
15.79 is ace. Thank you.

**Comment by Jmoores812** [comment]
> 

Same here. Try to play a video, and it almost restarts the app. Can't use at all. I haven't tried logging out, but would rather not have to.

**Comment by thunderdrum** [comment]
> 

same here. 
login Google account, can't play any videos.
logout the Google account, it works.

**Comment by hxd2772** [comment]
> With the new update (15.78 smarttube stable) I can't start any video on my FireTVstick (Tank)!!!
> 
> Every time I start a video the mainscreen appears.
> 
> edit: It seems the problem is only when I am logged in with my youtube account. Without account it works.

UZOgithub: You need to update to 15.79 to fix the issue

**Comment by kushariforyou** [comment]
The new update (beta) fixes things. Also you should not have created an issue to say thanks. This is to track bugs. You should have just replied in one of the other threads.

**Comment by thestuartcarson** [comment]
> The new update (beta) fixes things. Also you should not have created an issue to say thanks. This is to track bugs. You should have just replied in one of the other threads.

🫡🫡🫡🫡🫡🫡🫡🫡🫡🫡🫡🫡

**Comment by Jmoores812** [comment]
Thank you, I just was trying to find out if there was a fix because it
happened just after an update. I had never been to the help thread page
before and saw someone else had the same issue.
Thank you again
