### ISSUE TITLE
[Feature Request] 'Don't Recommend Channel' in long press menu.

### ISSUE THREAD

**Issue by therealdrl** [yuliskov/SmartTubeNext#1785]
I love this app, but I've run into an issue that's related to how YouTube handles things from the server side. Its how they differenciate 'Not interested' from 'Don't Recommend Channel' in the algorithm. I'll try to be brief.

YouTube is recommending channels I don't like or want in Smarttubenext. Normally, I handle this by opening the mobile app on my phone, finding a video from the channel, and choosing 'Don't Recommend Channel' from the menu. Recently, the Smarttubenext app on my TV and my other devices are getting different recommendations and I can't do this anymore. 

The result is Smarttubenext's home tab is flooded with recommendations I HAAATE and can't get rid of. And this is also because of server side handling. Choosing 'Not Interested' doesn't flag the algorithm to ignore the channel the video is from, but just that one video. So YouTube's algorithm will systematically feed _Every single video from that channel to me in batches of two to three videos per refresh,_ Presumably until I've blocked every last one individually. To stop a channel from showing up completely, 'Don't Recommend Channel' has to be used. 

Please add 'Don't Recommend Channel' support to the long press menu. YouTube's algorithm is testing my sanity, what little there is. I would be so grateful.

**Comment by g0r3** [comment]
I second this.

**Comment by therealdrl** [comment]
As an update, I decided to try loading the stock YouTube app on the same TVs as Smarttubenext and I found two new things. The first is that the stock app isn't recommendeding the extra channels Smarttubenext is. The recommendations are the same as my phone. Only Smarttubenext is pulling extra recommendations. I can't get the extra channels in seeing in this modded app on the official app to block them from even there. 

I also found that the official release also supports "don't recommend" in its "Not interested" menu. 

![20220903_230610](https://user-images.githubusercontent.com/97514302/188299959-cbc96676-6cd7-4d39-a5cd-6a5a4ba04c13.jpg)

So now I'm not sure what's causing this... leak, I guess, in the Smarttubenext app that's pulling extra recommendations for channels outside whatever my algorithm is collecting. Channels that aren't even in languages I speak. 

![20220903_231233](https://user-images.githubusercontent.com/97514302/188300034-205e1c95-8295-4a46-a3af-56aeec429e4a.jpg)

No matter how many I mark "Not interested" in the submenu, more come back. It's become a game of whack-a-mole and its exclusive to this app. I'm not sure what's causing it anymore.

**Comment by nbonfire** [comment]
I think this is a permanent change to youtube that's being rolled out in stages. I can no longer select don't recommend channel on the website or the app 😩

**Comment by therealdrl** [comment]
It's added!!! Thank you, thank you, THANK YOU!!!

**Comment by BobbyWibowo** [comment]
Was this removed at one point? I could no longer find it in the context menu, and it isn't an option to add it through the settings either

**Comment by therealdrl** [comment]
I noticed it's been appearing and disappearing at random as well. Just I decided to not make a big deal out of it. I figure it has more to do with YouTube hiding the option on videos they want to monitize than anything to donwith Smarttubenext's coding. Even on the stock app and stock website, "Don't Recommend Channel" isn't displayed on certain videos. That has to be for monetization reason on YouTube's part.

**Comment by BobbyWibowo** [comment]
> Even on the stock app and stock website, "Don't Recommend Channel" isn't displayed on certain videos. That has to be for monetization reason on YouTube's part.

Ah, that's interesting, I didn't know that, at least for the stock android TV app

I only have the desktop website as a reference, and iirc the option would at least be always available there
Though admittedly, the three dots menu, in which the "Don't recommend channel" option will be available, tend to take like 5+ seconds to be available to click after the homepage is supposed to have finished loading
