### ISSUE TITLE
Unable to unpin from sidebar

### ISSUE THREAD

**Issue by z1haze** [yuliskov/SmartTubeNext#1797]
There is not longer a button to unpin a pinned channel from the sidebar? I have looked at every single setting and section. How do we remove channels from the home page sidebar?

**Comment by z1haze** [comment]
![image](https://user-images.githubusercontent.com/6024725/185537084-206a2bd7-e472-4172-9bad-12f6f18ed3d0.png)
These channels are not subscribed to by me. They do not appear in my channel lost or subscriptions. Also when I lookup these channels, the avatars don't even match

**Comment by ManuLinares** [comment]
I have some playlists there that I "pinned" in a previous version, now they are stuck there as there is no option for removing those pinnes playlists.

**Comment by psy0rz** [comment]
same here. also cant pin new stuff

**Comment by psy0rz** [comment]
note that this seems to be broken for several months now.

**Comment by psy0rz** [comment]
lol it so happens i just found out how to fix it:

Go to Settings -> General -> Context menu

There you can re-enable the pin/unpin function!
