### ISSUE TITLE
Subtitles selection on second menu

### ISSUE THREAD

**Issue by tiabradford8** [yuliskov/SmartTubeNext#1807]
I'm not sure if this was intended or not, but now with recent update, rather than just being able to click the subtitle button and immediately choose the language, it now displays a secondary menu with several settings where you need to choose an option and then select a language. It's not a big deal, it's just most of the things I watch require subtitles and it was more convenient when the ability to simply choose the language was the default. Thanks for your great work on the app. I really appreciate it and use it all the time.

**Comment by 1Cr** [comment]
I also noticed this, and I am also a little irritated by it. I watch content in many languages, and occassionally (but not always) prefer subtitles. I would prefer to be able to turn subtitles on/off quickly, rather than having to go through an extra menu - as is the case since the update.

**Comment by PeterNjeim** [comment]
The latest update has made clicking the subtitle button enable or disable subtitles. Long pressing the subtitle button will open the menu now

**Comment by tiabradford8** [comment]
> The latest update has made clicking the subtitle button enable or disable subtitles. Long pressing the subtitle button will open the menu now

Thank you so much! You're the best.

**Comment by 1Cr** [comment]
Amazing!

**Comment by PeterNjeim** [comment]
> Thank you so much! You're the best.

Don't thank me lol, thank Yuliskov
