### ISSUE TITLE
Been seeing ads for two weeks on Firestick. 

### ISSUE THREAD

**Issue by Jokersflame** [yuliskov/SmartTubeNext#1825]
Hey y’all. I’ve tried clearing the cache, I’ve tried logging in and out, turning the block ad feature on and off again. Nothing is working. I’ve tried light and main launcher. 

If I have to watch another ad selling me bad insurance or a bad sandwich I’m going to go crazy. 

Any ideas how to help?

**Comment by Pr0mises** [comment]
That`s weird cause STN isn't able to show ads. Are you sure you're using STN and not SmartYouTubeTV ?

**Comment by Jokersflame** [comment]
> That`s weird cause STN isn't able to show ads. Are you sure you're using STN and not SmartYouTubeTV ?

Ah, you’re right. I’m using SmartYouTubeTV. I wasn’t aware there was a difference. Is SmartYouTubeTV still being updated and fixed?

**Comment by Pr0mises** [comment]
As mentioned in the readme [SmartYouTubeTV won't receive any frequent updates or fixes anymore](https://github.com/yuliskov/SmartTubeNext#q-what-to-do-if-i-like-smartyoutubetv-better)

**Comment by Jokersflame** [comment]
> As mentioned in the readme [SmartYouTubeTV won't receive any frequent updates or fixes anymore](https://github.com/yuliskov/SmartTubeNext#q-what-to-do-if-i-like-smartyoutubetv-better)

Understood! Thank you. I was unaware. I just downloaded SYTTV a while back and have just been using it as my main source of streaming stuff. I didn’t look into that there was a whole different app now or anything.

**Comment by Pr0mises** [comment]
You're welcome, if you have no further question be sure to close this issue.
