### ISSUE TITLE
Support finish_on_ended intent extra

### ISSUE THREAD

**Issue by UgglyNoodle** [yuliskov/SmartTubeNext#1840]
I'm the developer of [HopWatch](https://play.google.com/store/apps/details?id=com.ugglynoodle.hopwatch), a Reddit client for Android TV. HopWatch plays YouTube videos by launching an ACTION_VIEW intent. Currently only the official YouTube app is supported. However users have asked me to support alternative YouTube apps such as SmartTube so I'm planning to support this in the next release.

HopWatch sets the [`finish_on_ended` intent extra](https://developers.google.com/youtube/android/player/reference/com/google/android/youtube/player/YouTubeIntents#createPlayVideoIntentWithOptions(android.content.Context,%20java.lang.String,%20boolean,%20boolean)) which will make the YouTube app close when the video has ended, instead of auto-playing another video, so that the user returns to HopWatch. It would be great if SmartTube could also support this behaviour when handling a YouTube intent with the `finish_on_ended` intent extra. I have a pull request which implements this.

**Comment by Pr0mises** [comment]
This could be helpful for other applications as well, great work.

Also your Reddit approach with Hopswatch looks pretty good, just curious why it isn't OpenSource or am I missing something?

**Comment by UgglyNoodle** [comment]
Thanks, fixed by 5c832b8c6a882b397ee95d3519a5852a64137c84 and 9f6234301e139b42392272d8aca8322068674420.
