### ISSUE TITLE
Sponsorblock: skip muliple segments at once

### ISSUE THREAD

**Issue by CAFxX** [yuliskov/SmartTubeNext#1846]
In some videos there are multiple segments back-to-back that (depending on configuration) needs to be skipped.

Consider the following example timeline:

- Total video duration: 15 minutes
- 05:00 - 05:45 sponsored block
- 05:45 - 06:10 interaction reminder

Currently STN plays from the start to 05:00, skips to 05:45, plays for a fraction of a second from 05:45, skips again to 06:10, plays the rest of the video. This may seem a minor issue but it happens in a significant fraction of videos, and in extreme cases there are maybe 3-4 segments back-to-back to be skipped.

Ideally STN should instead play until 05:00 and skip directly to 06:10. If the notification is enabled for some of the skipped segment, a single notification could summarize the kinds of segments skipped.

**Comment by yuliskov** [comment]
Thanks for the feedback. Could you provide a video link for testing purposes?

**Comment by CAFxX** [comment]
This happens often with corridor videos. For example it happens at the beginning of this one: https://youtu.be/vurjXfUh2aM

**Comment by yuliskov** [comment]
Got it. Thx.

**Comment by CAFxX** [comment]
Will report back once this is released. Thanks!

**Comment by CAFxX** [comment]
Seems fine now. The only remaining issue is now https://github.com/yuliskov/SmartTubeNext/issues/1799.
