### ISSUE TITLE
false detection and skip

### ISSUE THREAD

**Issue by DanTheOracle** [yuliskov/SmartTubeNext#1852]
on every "cutting edge engineering" [channel] vid it detects the parts of his vids where he shows his dog as "ads" and skips them. this is obviously a false detection and i assume a bug? im not sure if this is the correct way to report these things so if im wrong i apologise. 

i dont believe he actually advertises in any of his videos and i have seen most of them. 

here is his latest vid and it cuts out 3 sections of vid, the first was his dog but ive not got to the other 2 yet to confirm but i assume it also is. https://www.youtube.com/watch?v=ahyLHhdrNyU&t=646s

thanks 
Dan

**Comment by fastnlight0** [comment]
Sponsor block is different software than STN. Also, Sponsor block is crowd sourced, meaning other people declare the segments to skip. If the segments are incorrect, you can downvote them with the SponsorBlock extension on a computer/phone (https://sponsor.ajay.app)
