### ISSUE TITLE
The initial YouTubeSignInService signin request is not handled by the http proxy

### ISSUE THREAD

**Issue by amit-gshe** [yuliskov/SmartTubeNext#1860]
At the begining of the app startup, The app send an authentication request to exchange auth token by the `YoutubeSignInService`. But this auth requst is too early that the app proxy is not configured at that moment, so the request will get failed . And the app will get stuck in an loading screen for more than 30 seconds. Maybe we need to bring the proxy setup forward or delay the auth process so that all network request will get handled by the proxy setting.

The auth request is the code below:
https://github.com/yuliskov/MediaServiceCore/blob/e3ab9cdd440e7b4259edb530afa83b6300850cbf/youtubeapi/src/main/java/com/liskovsoft/youtubeapi/service/YouTubeSignInService.java#L157

The proxy setup is in `SplashPresenter#applyRunOnceTasks`:
https://github.com/yuliskov/SmartTubeNext/blob/117e7d3e9c487d218b3a36f03371eac5d0419eb6/common/src/main/java/com/liskovsoft/smartyoutubetv2/common/app/presenters/SplashPresenter.java#L72-L85

**Comment by soarpoon** [comment]
exactly， hope it can be fixed.

**Comment by soarpoon** [comment]
The new version 15.99 has fixed it.
