### ISSUE TITLE
History

### ISSUE THREAD

**Issue by sixerstyle** [yuliskov/SmartTubeNext#1876]
Hello, I am using smarttube 15.81 on a fire tv 4k max stick. I have the problem that the history is not saved. But I can see the history of the videos I've looked at on the pc. any suggestions?
greetings
sixer

**Comment by Reyshyram** [comment]
Hello, it’s the same for me, with STN the history isn’t saved but it works with the official YouTube app

**Comment by reptail** [comment]
For me, on a Sony Bravia (2015) also using latest Stable v15.81, it recorded history on Monday (September 19th). 
But nothing were recorded for videos watched the next day, Tuesday (September 20th).

**Comment by koffeedude** [comment]
Same issue for me on Firecube

**Comment by Ivan171** [comment]
I'm having the same issue on my Android TV (TCL model)

**Comment by AiWABR** [comment]
Same in fire tv 4k

**Comment by Davegb** [comment]
Same in Chromecast 4K.

**Comment by SexyNick** [comment]
I'm having the same issue on a 2019 Shield TV Pro. Videos are only saved to my history if they're viewed on another device. It started a few days ago, then seemed like it was fixed, and then started not saving them yesterday. I'm on version 15.81.

**Comment by troraklo** [comment]
Hi, same issue for me on a TCL android TV since 4 o 5 days.

**Comment by Sennat0r** [comment]
Seems to be a common issue. Probably the author is already aware of and working on it.

**Comment by xaxdrax** [comment]
I too have the same issue. When using the official Youtube App, it saves the history.

**Comment by fardy316** [comment]
Had the same issue on Android TV with version 15.81.
Just updated to latest 16.04 proposed update and issue is now resolved.

**Comment by sixerstyle** [comment]
Is fixed with new version, thx
