### ISSUE TITLE
4K/60FPS/HDR playback 

### ISSUE THREAD

**Issue by costinmx** [yuliskov/SmartTubeNext#188]
Hi,
Smart Tube Next video player does not run smoothly 4K/60FPS/HDR videos (~25-30 Mbps). Lower bitrates are working fine, but above 25Mbps there are skipped frames. Observed on Sony ATV3 2019 platform.
SmartYT or original YT app, plays any video at any rate with no issue whatsoever. 

May be a problem caused by low buffering / insuficcient bandwidth / drained proceesing power, during SmartTubeNext playback. A short pause on the video makes the playback smooth again on resume, but only for 5-10 seconds. This is the only app that struggles with 60FPS HDR videos on this TV. Hope it can be fixed.

**Comment by foreveryoungforty** [comment]
Indeed same here on Sony 4k ATV see #139

**Comment by foreveryoungforty** [comment]
For me the problem is solved with release 10.29 !

**Comment by costinmx** [comment]
That is correct, problem seems solved! ~30Mpbs videos (like 4K/60FPS/HDR or high bitrate 4K/60FPS) running smoothly now on SmartTube, exactly as in Original YT app, or SmartYT.  Some lag stil visible 2-3 secs on very high rendered scenes in 30Mbps or above videos, but its very rare and it does this on all youtube players.
Pretty sure it was not abut buffering, as I tried all settings (Medium and High) with no difference. More like a codec/player issue.  I think issue may be closed.
Thanks, Yuliskov!
