### ISSUE TITLE
Refresh button

### ISSUE THREAD

**Issue by buthig666** [yuliskov/SmartTubeNext#1935]
A refresh button (at the top of screen or in long press menu) would be verry helpful.  I have to constantly check real world events and news.

I find myself constantly backing out of a section (I live in the Subscriptions section half of my workday,)  to refresh the videos because sometimes on the wrong day I will have 20 channels drop information in 10 mins.  The only way to refresh a section is to back out scroll up or down away from the section then scroll back to the section.  

I think it would be reasonable and verry functional to have the option of a refresh button at the top of the screen beside the search button.  

Thank you so much for your hard work.

**Comment by TempestoGuy** [comment]
You don't have to scroll at all you can just click the section again without backing out and it refreshes.

A refresh button option is a good idea though.

**Comment by buthig666** [comment]
Oh ok, I have no idea why I never tried that.  

feeling pretty silly right now.  Thanks for your suggestion.

**Comment by PeterNjeim** [comment]
Please close issues that you feel are resolved. If you still want a dedicated refresh button, leave the issue open, otherwise, close this as resolved
