### ISSUE TITLE
Kindly Add Nigeria to country list

### ISSUE THREAD

**Issue by juliustip** [yuliskov/SmartTubeNext#2047]
I can't find Nigeria in country list. Would be great if added.

**Comment by drewbitt** [comment]
Quick first PR if you're interested [common/src/main/res/values/countries.xml](https://github.com/yuliskov/SmartTubeNext/blob/fa04ad73cb7ff5dfa1312e9714d8c62d071a24bc/common/src/main/res/values/countries.xml)

**Comment by juliustip** [comment]
Thanks, now submitted.
