### ISSUE TITLE
History re-enables itself after disabling it by using STNext

### ISSUE THREAD

**Issue by MonsieurNoobNoob** [yuliskov/SmartTubeNext#2055]
Hello there !

First, thank you so much for this app, it's gold! It's so life changing compared to the official app!

Since my last update I encounter this bug, here the steps to reproduced it:

_ In my YT preferences (on the official YT website) I chose to deactivate the YT history, the YT history is deactivated and empty

_ When I watch YT on my PC or Mobile the history remains deactivated and empty

_ However, when I watch a video via SmartTubeNext, my history is automatically reactivated and the videos I’ve watched begin to be saved in it

_ The history is then active everywhere (YT PC and mobile), and I have to manually deactivate it again and clear it

_ It remains deactivated until I re-watch a video via STNext again

I didn't have this problem before, but I hadn't updated for several months so I don't know what version I was on before the bug appeared.

Thanks in advance and thanks again for your app!

**Comment by antch** [comment]
I've been running into an issue which I'm guessing is probably related. I DO have Watch History enabled on my son's account and every he uses STN I get an e-mail from Google saying that Watch History was enabled. This started on Dec 7th, so the issue was almost definitely caused by whatever Beta release was available then (I update the app often).

**Comment by gfshrub** [comment]
Have the same issue as MonsieurNoobNoob. Watch History is reactivated after using STN beta. Started a couple of weeks ago and continues with version 16.52

**Comment by Hellhammer06** [comment]
I have the same issue. My browsing history is always disabled in my Google account settings, but after using version 16.58 and previous beta versions, the history is enabled again. There was no such thing on version 16.37 (Xiaomi MiBox S, Android TV 9)

**Comment by UkeHa** [comment]
yeah, me too. I'd love the setting to stay the same and not change after each use!

**Comment by antch** [comment]
@UkeHa This is fixed, at least in one of the Beta releases

**Comment by MonsieurNoobNoob** [comment]
Yeah seems to be fixed with the latest version, thanks a lot!

**Comment by fbnkrs** [comment]
I have this issue constantly over and over again, from version to version.

**Comment by emes81** [comment]
I believe I have found a workaround: under Settings / General / Set Up Sections, you need to deselect Home and History. It seems like navigating onto them re-enables watch history. But also, you don't need these sections if you've disabled watch history!
