### ISSUE TITLE
Search results limited to 20 Videos

### ISSUE THREAD

**Issue by sixerstyle** [yuliskov/SmartTubeNext#2076]
Hello,
im using SmartTube V16.37 on a Fire TV Stick.
For a few weeks, the result of a search has been limited to exactly 20 videos.
Any Hints? 
there are no problems in the original app

greetings

**Comment by lerootoja** [comment]
The same on Xiaomi Stick. Only 20 search results. A little bit annoying.

**Comment by sixerstyle** [comment]
Yes with new Version it works for me too, thx
