### ISSUE TITLE
Long delays on open and play

### ISSUE THREAD

**Issue by gabizro** [yuliskov/SmartTubeNext#2082]
Hello
I'm using MiBox4
For few days ago,maybe a week, I encountered this problem. 
It was on 16.37 stable installed when launched so no changes was done in meantime.
When I open application it opens fine menus are OK but instead of preview of clips I have a spinning circle for long time 20-30 second or more then then main window is populated with clip preview windows.
When I select and play one clip player start, then again spinning circle for long time tens of seconds then black screen for around 10-20 seconds then after almost 1 minutes image appears but is only first frame like it was paused then after 2-3 seconds start playing.
From here all works fine,play pause,forward backward etc, returning to main view also OK , but once I select other clip to play same problem, spinning circle for long time, black screen, first frame then play.

First time I think it was internet problem so restarted box but no result then I restarted router but also no result
I tested other apps and all was working fine.
Youtube app opens in 2-3 seconds max  and clips open almost instant when selected,and play fine.

1- Next clean cache and data  for SmartTubeNext ,no positive result.
2- Uninstall and install again, no positive result.
3- Reset MiBox to factory and start over again, no positive result.
4- Reset router to factory settings
    Reset MiBox to factory settings still no positive result
Tested with my account or without account result are the same.
Now with 16,58 repeated steps above but still same problem.

How can I diagnose that?
Will debug build will give me some info on what is happening or what is wrong during that spinning circle period?

**Comment by gabizro** [comment]
Now is worst.
Minutes have past and still spinning circle.
There is something odd.
Internet works,youtube works,[SmartTubeNext doesn't works.

Try to build debug version
but error seems I need Android SDK but which one?
 com.android.builder.errors.EvalIssueException: SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable

**Comment by lixenstrand** [comment]
I have this issue to. I'm on nvidea shield 2019 tube

**Comment by gabizro** [comment]
Problem was from ISP
Switched me back to only IPv4 and all works fine now.
