### ISSUE TITLE
SmartTube persistently enables YouTube watch history

### ISSUE THREAD

**Issue by Azuri001** [yuliskov/SmartTubeNext#2098]
Whenever I watch a video in SmartTube, for some reason the app overrides my YT settings and enable saving Watch History.

**Comment by emes81** [comment]
I believe I have found a workaround: under Settings / General / Set Up Sections, you need to deselect Home and History. It seems like navigating onto them re-enables watch history. But also, you don't need these sections if you've disabled watch history!
