### ISSUE TITLE
Feature request: Absolute dates in video player

### ISSUE THREAD

**Issue by rodalpho** [yuliskov/SmartTubeNext#2120]
As of a couple months ago (I think) the way the video player displays dates changed. It used to switch between relative date like "2 years ago" and absolute date like "January 17 2022". Now it _only_ shows the relative date. 

My request is to either restore the previous behavior where it switches every time or allow the user to specify their preference for relative or absolute date in the configuration.

**Comment by DTK21** [comment]
I typically use both the stable and release version but as far as I know the 16.37 version has all videos exact dates in the Video UI. Wish there was an option to choose exact or approximate date as well. Though it seems to make more sense to only have the exact

**Comment by rodalpho** [comment]
It does now, yes! Must have been changed in the past 2 days.

**Comment by DTK21** [comment]
Where do you see the Absolute date option? I'm still getting the 2y ago for the updated beta

**Comment by DTK21** [comment]
> It does now, yes! Must have been changed in the past 2 days.

Where do you see the Absolute date option? I'm still getting the 2y ago for the updated beta

**Comment by rodalpho** [comment]
Actually, it's weird. The ShieldTV in my bedroom has absolute dates and in my living room, "2y ago". I dunno. 

It's a small issue, and the developer is in Ukraine so he likely has other things on his mind, but I do find it annoying.

**Comment by rodalpho** [comment]
I managed to fix this by clearing cache+data for the app (basically removing all configs) and reconfiguring the app from scratch. Such a weird problem.

**Comment by DTK21** [comment]
Bet, I gotta try this when I get home. Hopefully it works, I'll accept the small hassle of re-linking my account

**Comment by DTK21** [comment]
Yep this most definitely worked, wish I did a backup beforehand but setting things up again isn't a problem
Probably best to close it out now

**Comment by rodalpho** [comment]
I assumed any backup would contain whatever caused the problem so started fresh, but it would have been worth trying. Happy you're back in business too!

**Comment by DTK21** [comment]
Yeah I tested with another device I had to re-setup, clearing data is just the best method overall then tweak your settings then make a backup of that for any future problems
