### ISSUE TITLE
Unable to switch accounts on beta 16.69

### ISSUE THREAD

**Issue by pi2squared** [yuliskov/SmartTubeNext#2124]
Just updated to 16.69 and the account switch menu appears to be broken now.  Unable to make a selection (move cursor up or down) and pressing OK on the currently selected account just seems to reopen the account select menu over and over again. 

edit: Just updated to 16.70 and it's fixed! Stellar work

**Comment by CBozsik** [comment]
Just did the same and same issue.

**Comment by pi2squared** [comment]
Fixed with 16.70!
