### ISSUE TITLE
Secondary Menus

### ISSUE THREAD

**Issue by Scott347a3** [yuliskov/SmartTubeNext#2125]
All click thru secondary/sub menus do not work. I recently upgraded to v16. 69 when this happened. Primary menus still work.

I am on an Onn 4k TV firmware version 1.01.36 (Android TV 10)

**Comment by Scott347a3** [comment]
Updated to STN 16.70 just now and it works again. This is a fantastic app. Thank you!

Slava Ukrani!

**Comment by drogga** [comment]
@Scott347a3 Is there a reason on why you still haven't closed this ticked ?
...since I see that it's resolved...

**Comment by drogga** [comment]
@yuliskov I think that this can\should be closed...
