### ISSUE TITLE
History blank 

### ISSUE THREAD

**Issue by Jawknee21** [yuliskov/SmartTubeNext#2165]
History not coming up

**Comment by gergor888** [comment]
I have the same issue. Tried log out and log in again. Cleared Cache and Data. Happening on all of my android TV units.

**Comment by gazmeeek** [comment]
I’ve got the same issue unfortunately.

**Comment by rixh** [comment]
Same at this end no history!
Must be a bug in the software hopefully gets fixed ASAP.

**Comment by gergor888** [comment]
The latest update fixed the issue for me! Thanks!

**Comment by gazmeeek** [comment]
Fixed for me too, great stuff thanks.

**Comment by drogga** [comment]
@Jawknee21
Perhaps maybe close it if it's resolved...?

...IDK why nobody \ no one is closing the resolved issue tickets here, that's why there are currently 1.2K of them still open...

**Comment by Jawknee21** [comment]
I didn't realize this was possible

**Comment by Jawknee21** [comment]
I doubt anyone even comes back to these once the problem is fixed 😂
