### ISSUE TITLE
[BUG] Saving playlists

### ISSUE THREAD

**Issue by Ackmard** [yuliskov/SmartTubeNext#2176]
The option to save a playlist doesn't appear in the context menu anymore. You can only add to a new or existing one if the options are enabled, but you cannot just save someone's playlist like you used to. No idea when it disappeared and if it was intentional but the option still exists in the context menu settings.

**Comment by github-monkey** [comment]
Same. Have STN installed on two devices (Xiaomi MiBox 4) and Save to playlist has disappeared from connect menu on both devices. Can pin to sidebar, but context option to save a playlist to the playlist section is gone, even though it still appears in the settings menu.

**Comment by github-monkey** [comment]
@Ackmard 17.20 seems to have fixed the issue for me. You?

**Comment by Ackmard** [comment]
Yeah it seems fixed. Not sure what exactly made it appear but it's there now.
