### ISSUE TITLE
Need a way to  completely disable VP9

### ISSUE THREAD

**Issue by borislip** [yuliskov/SmartTubeNext#218]
My Sony Bravia (2015, FHD) TV plays VP9 at 5 fps or so, which is pretty much unwatchable. Choosing "FHD, 60fps, AVC" profile doesn't seem to prevent the player from ever trying VP9, for example, it has switched to 720p VP9 on me on many videos, which were available in 720p AVC (mainly abc7ny news vids), that would have been fine. Having to manually switch it over to AVC on a per-video basis is extremely annoying and gets old really fast.

**Comment by chronos1nside** [comment]
I have the same TV (Sony Bravia 2015 FHD) running with Android 7.0 and it would be really helpful to select a default profile between AVC and VP9.

Thanks in advance and keep up the good work.

**Comment by RedTestament** [comment]
I have the same problem, no response since.
https://github.com/yuliskov/SmartTubeNext/issues/174

**Comment by chronos1nside** [comment]
Apparently, with the latest update (10.31), I no longer have issues with the framerate; I will continue testing until being absolutely sure.

**Comment by borislip** [comment]
It does seem like it no longer attempts to run the VP9 streams here indeed. Thanks!

**Comment by chronos1nside** [comment]
So far, so good; @borislip should close this issue now, I guess.

Was your issue resolved @RedTestament ?

**Comment by RedTestament** [comment]
> 
> 
> So far, so good; @borislip should close this issue now, I guess.
> 
> Was your issue resolved @RedTestament ?

The latest release solved my problem, I think the new option to select the video codec and the fix to solve the framerate was the problem, in my case is solven and the App perfomance is now flawless.

**Comment by borislip** [comment]
Ok, lets close it then! Thanks!
