### ISSUE TITLE
Play video with ads

### ISSUE THREAD

**Issue by stev412** [yuliskov/SmartTubeNext#2191]
I love this app. It amazing how it can skip ads , sponsors and subscribe reminders.  With some videos though, I like to watch without skipping the intro.  Would it be possible to have a one time ad enable option.  Like if you hold the button on a video it gives you lots of options, one of these could be "play with ads" or "play with adblock disabled". .

Then if you just click the next video normally the next time it plays with adblock.

**Comment by cuynu** [comment]
This app is designed for ad-free YouTube, Like many other unofficial YouTube API apps, there are no ads. It would be difficult to implement ads into their apps, and they wouldn't do it either because it's time consuming and useless

**Comment by cuynu** [comment]
Here's a question already in the FAQ:

Q: Can I whitelist ads on some channels?

A: no, this is not possible. SmartTubeNext does not have any code to display ads. Adding this functionality would actually take time and effort, which is instead spent on adding useful features and fixing bugs.

**Comment by stevensmedia** [comment]
Skipping the intro is a "sponsorblock" setting which you can turn off in the settings.

**Comment by stev412** [comment]
Ok. Thanks for the replies.
