### ISSUE TITLE
subscribe a channel

### ISSUE THREAD

**Issue by Serialski** [yuliskov/SmartTubeNext#223]
I cant find option to subscribe a channel in smart tube next app ?

**Comment by foreveryoungforty** [comment]
Symbol in player , bottom row - 3rd from right.

**Comment by Serialski** [comment]
got it tnx. 

what about when Searching for a channel, I cant open founded channel, I only can open its videos

**Comment by foreveryoungforty** [comment]
Long press a video and choose go to channel

**Comment by aecarvalho** [comment]
> got it tnx.
> 
> what about when Searching for a channel, I cant open founded channel, I only can open its videos

Close the issue please if your issue is resolved, it will help the developer to focus on other relevant issues.

**Comment by foreveryoungforty** [comment]
@Serialski can you please close the issue to keep the surey of open issues clear

**Comment by Serialski** [comment]
ok tnx :)
