### ISSUE TITLE
[Regression] In 17.20 the image is zoomed in

### ISSUE THREAD

**Issue by daf0x** [yuliskov/SmartTubeNext#2243]
I just updated to [17.20](https://github.com/yuliskov/SmartTubeNext/releases/tag/17.20s), and I noticed that the screen is now slightly zoomed in. It's enough so that text at the top and bottom of videos like [this](https://www.youtube.com/watch?v=q9LWzA-JE0Y) become hard to read.

The zoom is uniform, so both left/right and top/bottom of the screen are cut of.

There doesn't appear to be a way to correct this, the video zoom is set to `Default`, but none of the options `Fit width`, `Fit height`, `Fit either width or height`, `Stretch`, or `100%` make any difference to the zoom level.

**Comment by dgeelen-uipath** [comment]
Hmm, strangely today I opened smart tube and continued the above video and the problem was gone. Maybe just a restart fixed it, so please close this issue for now.

**Comment by daf0x** [comment]
Hmm, strangely today I opened smart tube and continued the above video and the problem was gone. Maybe just a restart fixed it, so please close this issue for now.

**Comment by daf0x** [comment]
Hmm, strangely today I opened smart tube and continued the above video and the problem was gone. Maybe just a restart fixed it, so I'm closing this issue for now.
