### ISSUE TITLE
Not installed

### ISSUE THREAD

**Issue by akeilox** [yuliskov/SmartTubeNext#2246]
I am getting app not installed err when trying to update , same err when trying to install manually STubeNext_ststable_v17.20_r.apk

on mi stick 4k

any ideas why?

**Comment by sergienko4** [comment]
+ 1

**Comment by sergienko4** [comment]
i cleaned internal memory and it works good now :-) 
@akeilox try it

**Comment by MailYouLater** [comment]
I often find that my device's internal storage is too full to install/update apps.  Most of the time I can go to my Storage settings and clear cached data to get enough space to complete the installation.  Occasionally I find that I actually need to delete some files or uninstall some apps to claw back enough space.

There have also been a few times when I've been fairly certain I already had enough space, but found that I was able to perform the desired update/install after either clearing the data, or uninstalling the updates of the Google Play Services app.  I can only speculate regarding why doing either of those would make a difference, but it's worked for me a number of times almost always with Beta releases of STN.

**Comment by akeilox** [comment]
> i cleaned internal memory and it works good now :-)
> @akeilox try it

That was the issue indeed. The error message could be more descriptive.

**Comment by akeilox** [comment]
> I often find that my device's internal storage is too full to install/update apps. Most of the time I can go to my Storage settings and clear cached data to get enough space to complete the installation. Occasionally I find that I actually need to delete some files or uninstall some apps to claw back enough space.
> 
> There have also been a few times when I've been fairly certain I already had enough space, but found that I was able to perform the desired update/install after either clearing the data, or uninstalling the updates of the Google Play Services app. I can only speculate regarding why doing either of those would make a difference, but it's worked for me a number of times almost always with Beta releases of STN.

Thank you for the insight. I’ll also follow BETA releases.
