### ISSUE TITLE
Restore more granular playback speed options 

### ISSUE THREAD

**Issue by hiroo916** [yuliskov/SmartTubeNext#2254]
I'm not quite sure when the change happened since there have been a few updates recently (as of 2/23/23) but as of version 17.20, the speed options have been reduced to only 0.25 increments.

I'm here to request that more speed options be put back because the 0.25 jumps are too big. Going from 1.0 to 1.25 is just too much on some videos. For videos that I want to watch "naturally" but reduce the time, more granular speeds between 1.0 and 1.5 are needed. Above 1.5, I think the 0.25 increment is ok.

And I found the previous available 0.95 option really useful for watching foreign language videos that I am learning or have some comprehension of, because it made it easier to decode the words without making it sound unnaturally slow. Below that 0.75, 0.5, 0.25 is ok.

Now for those who thought there were too many options, I also was once annoyed that there were so many options, because clicking and scrolling through the menu was a bit troublesome, especially in the previous UI where clicking the Clock icon would pop up the full menu of speeds and if you were at 3.0x and wanted to go back to 1.0x, you would have to scroll all the way back down. However, I'd made the suggestion (not claiming sole credit) to have single click turn on/off to toggle speed-adjusted playback, and click-hold pop up the speed adjustment menu. When that got implemented, that reduced a lot of cases of having to click through the whole menu because you could go back and forth between 1.0 and selected speed with one toggle click.

I later got the Rii K25 remote control for my Shield (because I was sick of changing batteries on the slim remote) and discovered a great feature: the PageUp/PageDown buttons worked on SmartTubeNext to adjust the playback speed up and down without going into any menu and it was great to be able to adjust speed at any time without having to go into the UI and interrupting playback. So this might be another option for people annoyed with the longer menu, find an alternative remote with PgUp/PgDown keys. Not sure what other remotes work for this but the K25 does.

So please put my vote in for restoring the previous longer list of speed options: 0.25, 0.5, 0.75, 0.95, 1.0, 1.05, 1.1, 1.2, 1.3, 1.4, 1.5, 1.75, 2.0, 2.25, 2.5, 2.75, 3.0.

If it needs to be configurable in the Settings, maybe just have a full option list of speeds from 0.25 to 3.0 in 0.05 increments and the user can select the ones they want to appear in the menu.

**Comment by costinmx** [comment]
No offence, but you should really read the description before updating. There is a specific STN setting in place for setting this increments to previous smaller values. This is at least the 3rd topic open for the same non-existing issue...

**Comment by hiroo916** [comment]
I went through the settings options in quite some detail before coming here and couldn't find anything related to setting the speed increments. Can you point out where that is?

**Comment by costinmx** [comment]
[https://github.com/yuliskov/SmartTubeNext/releases/tag/17.20](https://github.com/yuliskov/SmartTubeNext/releases/tag/17.20)
17.20 Beta Pre-release
@[yuliskov](https://github.com/yuliskov) yuliskov released this 4 days ago


SponsorBlock: improved segments accuracy
**Added option to change the size of the available speeds: Settings/Player/Misc/Long speed list**
Previous release bugfixes

**Comment by costinmx** [comment]
You just have to check the Changelog at the time you update.

**Comment by hiroo916** [comment]
Thanks for pointing that out. I missed it because I looked through all the options that mentioned the playback speed, but this one is buried over more level down under misc.
