### ISSUE TITLE
No longer having access to sign in content

### ISSUE THREAD

**Issue by sudharsannr** [yuliskov/SmartTubeNext#2266]
Version: 17.20
Issue:
Main Sidebar -> Playlists gives the error 
```
Can't load content. 
1) Check date and time on the device. 
2) Check network connection. 
3) Check your proxy settings. 
4) Try to sign in to your account. 
5) Maybe there is nothing in here.
```

Tried logging in through Accounts -> Sign In. Signed in and the app refreshes but the profile bar doesn't change to the account. 
Related issue: #851

**Comment by sudharsannr** [comment]
Strange behaviour - I logged in two times and listed Sign in options as:

1. None
2. 
3. 

Anyhow, closing this since the issue didn't appear after resetting the data and logging again.

**Comment by DJTOMATO** [comment]
This issue still persists
Same reports of the issue are
#3292 
#2122
#1816
#851
