### ISSUE TITLE
Video Keep Buffering On Firestick TV

### ISSUE THREAD

**Issue by XanderBGaming** [yuliskov/SmartTubeNext#2270]
I've been having the issue where. it plays the video and then buffers for a long time after then goes back to buffering. Im guessing it has to do with YouTube way of how they now deal with adblockers.

**Comment by jlitz** [comment]
Yes been getting a lot of buffering lately.   Not present in TVBro browser  so maybe related to ad block  I dont know but its not my ISP as all other apks work fine.

**Comment by chrisfederico1** [comment]
Happening a lot lately for sure . Almost to point that its unwatchable .

**Comment by frugalhuman** [comment]
I've had this issue too but my internet is also pretty bad so I can never tell if it's actually the app or my internet

**Comment by nwb99** [comment]
I downgraded to the last stable 16.93
I'm going to see if I still get the issue

**Comment by lollilol** [comment]
I have the issue too on the Mi TV P1 55"
It works fine for about 5 minutes after a reboot and then it starts lagging. It's definitely not an Internet issue because I see frame drops.

**Comment by theuserwhoisnotadeveloper** [comment]
I have a similar issue on x96 mini with slimboxtv os 9.4. 720p 1.5 Mbps videos buffer a lot even thought the internet connection is more than capable of playing it. even if I switch to 480 or lower resolutions the buffering takes a lot of time.

**Comment by jlitz** [comment]
seems fixed with latest

**Comment by aecarvalho** [comment]
fixed with 17.26

**Comment by ClementNerma** [comment]
@XanderBGaming could you please close the issue if it's solved for you in the latest release? :)

**Comment by Sebastin3244** [comment]
Every time I go to sign in, a screen reader called Voice View doesn't read the code to me.  How can this get fixed?
