### ISSUE TITLE
10 Hour+ Video Constant Buffering

### ISSUE THREAD

**Issue by truehd24** [yuliskov/SmartTubeNext#2277]
Version 17.24 on Sony A80J.
Most videos play just fine at full resolution, but when trying to play a 1080p 10+ hour video the player buffers every few seconds of playback. The same videos played back just fine on previous versions.

**Comment by Matze50679** [comment]
Had the same problem, have now installed the beta and here the problem does not exist

**Comment by truehd24** [comment]
Fixed in 17.26
