### ISSUE TITLE
Video source isn't working or time is wong

### ISSUE THREAD

**Issue by Red-Baran** [yuliskov/SmartTubeNext#2278]
Pretty much any video over 5 minutes or so the error in the title comes up.
This started at 14.23_r and is also happening with 24
Running a Google 4k TV dongle.

**Comment by Dermuh** [comment]
Same here on Amazon TV stick

**Comment by gate1975mlm** [comment]
Same here on Shield TV and Sony A80J TV

**Comment by aecarvalho** [comment]
Same for Mi 4A 40, still facing the issue at build 17.25

**Comment by Red-Baran** [comment]
Just an update if you don't enable Material you revanced extended options don't crash

**Comment by Crononaut** [comment]
Same problem Shield TV Pro, running 17.25

**Comment by Red-Baran** [comment]
Yea still an issue with 17.25
Also it crashes and I just get stuck on a black screen once and a while.

**Comment by m0menti1337** [comment]
Same on tcl android tv, every 5 minutes it displays this message and sometimes it crashes.

**Comment by aecarvalho** [comment]
The Issue seems to have been resolved in build 17.26 for Mi 4A 40 TV, thanks @yuliskov

**Comment by Red-Baran** [comment]
Yep fixed on the Google TV dongle.

These developers are the f*cking awesome. Thanks for the quick fix and an awesome project!

**Comment by Red-Baran** [comment]
Fixed
