### ISSUE TITLE
Less video speed options

### ISSUE THREAD

**Issue by ManScho** [yuliskov/SmartTubeNext#2285]
Hi,
I really miss the option to have more options for Video speed. Befor there was more range between 1x and 1.5x.

**Comment by FabioM3** [comment]
An option with checkboxes to select what velocitys user wants will be appreciated.
But an minimalistic approach is to use: 1x, 1.25x, 1.5x, 1.75x and 2.0x.

**Comment by FabioM3** [comment]
There's an option to use more speeds in v17.
Search before post.

**Comment by ManScho** [comment]
> There's an option to use more speeds in v17. Search before post.

I know but before there were more options the were 1.3x 1.4x but now they are no more avalible.
