### ISSUE TITLE
ATV smart youtube tv bridge cannot be installed

### ISSUE THREAD

**Issue by mcitew** [yuliskov/SmartTubeNext#2307]
I installed STN beta 17.35 on sony TV, it keeps prompting me to enable voice search and install ATV smart YouTube TV bridge but it cannot be installed.

No such problem on the hand phone.

**Comment by zitev** [comment]
The problem is the same with me, on my both Sony TV..

**Comment by cuynu** [comment]
Only device with no stock YouTube TV installed can install bridge

**Comment by tcpaulh** [comment]
Same problem here on Nvidia Shield tube 2019

**Comment by averred** [comment]
Same here on Sony TV

**Comment by mcitew** [comment]
It is said that I have to uninstall the TV version of the preinstalled YouTube, but I don't seem to find a way to do it on the Sony TV. 

Now I disable the "enable voice search".

**Comment by emranovin** [comment]
> It is said that I have to uninstall the TV version of the preinstalled YouTube, but I don't seem to find a way to do it on the Sony TV.
> 
> Now I disable the "enable voice search".

You can uninstall stock Youtube app without root! you just need to install 'adb appcontrol' on windows ad connect with wifi.
Even though I uninstall the original Youtube app from tv I still have problem with bridge and it fails on install (I even try amazon version on my sony tv. It installed but didn't work)
Any new soloution?

**Comment by jiznon** [comment]
I've also uninstalled com.google.android.youtube.tv via adb, and also cannot install the Bridge. Any help would be greatly appreciated! Sony Bravia A80J. Error: "App not installed."

**Comment by AshotN** [comment]
`adb uninstall` doesn't truly remove the package. So far I don't think there is a way, without root, to truly remove the YouTube app and install bridge.

**Comment by Gamersboygb** [comment]
> > It is said that I have to uninstall the TV version of the preinstalled YouTube, but I don't seem to find a way to do it on the Sony TV.
> > Now I disable the "enable voice search".
> 
> You can uninstall stock Youtube app without root! you just need to install 'adb appcontrol' on windows & connect with wifi. Even though I uninstalled the original Youtube app from tv I still have problem with bridge and it fails on install (I even try amazon version on my sony tv. It installed but didn't work) Any new soloution?

Same problem for google impex tv

**Comment by gabrieldevsouza** [comment]
Same problem for onn 4k

**Comment by JGuilhermeCoelho** [comment]
Same problem for Philips Ambilight 4k

**Comment by matteopaolucci** [comment]
I followed this guide and works on Google TV (Sony Bravia)
https://techmogulchannel.com/tutorial-how-to-install-smarttubenext-smart-youtube-tv-to-chromecast-with-google-tv/

Maybe it is not the last version, but it works.

**Comment by jiznon** [comment]
> I followed this guide and works on Google TV (Sony Bravia) https://techmogulchannel.com/tutorial-how-to-install-smarttubenext-smart-youtube-tv-to-chromecast-with-google-tv/
> 
> Maybe it is not the last version, but it works.

What does this have to do with this thread? Where in this spam ridden link does it install the Bridge?

**Comment by jb89728** [comment]
Installed fine on my Bravia but immediately closes when launching. Jim’s  iPhoneOn Jun 6, 2024, at 11:42 AM, jiznon ***@***.***> wrote:﻿

I followed this guide and works on Google TV (Sony Bravia) https://techmogulchannel.com/tutorial-how-to-install-smarttubenext-smart-youtube-tv-to-chromecast-with-google-tv/
Maybe it is not the last version, but it works.

What does this have to do with this thread? Where in this spam ridden link does it install the Bridge?

**Comment by matteopaolucci** [comment]
> > I followed this guide and works on Google TV (Sony Bravia) https://techmogulchannel.com/tutorial-how-to-install-smarttubenext-smart-youtube-tv-to-chromecast-with-google-tv/
> > 
> > Maybe it is not the last version, but it works.
> 
> What does this have to do with this thread? Where in this spam ridden link does it install the Bridge?

Sorry, i was having a problem with installing the app and I was searching among the issues. I wrote in the wrong one.
