### ISSUE TITLE
3 little tweaks in UI

### ISSUE THREAD

**Issue by onolox** [yuliskov/SmartTubeNext#231]
First, when we hold ok button we need to let it go to show the menu, this is an anti-pattern. Make it like the Smart Youtube tv, when we hold the button it shows the menu after the 3s.

Second, in the menu that appears after ok is hold, when we select an item, the menu have to close.

Third, the speed menu have to start from the actual velocity, not the top of the menu.

Thanks!

**Comment by Jahfry** [comment]
Agreed. First/second comment were what I came here to report if not already done. 

(Nvidia Shield Pro 2019)

**Comment by samschafer** [comment]
First comment has been on my mind for a while. When I first downloaded the app, I didn't even know if there were hold down menus.

**Comment by onolox** [comment]
Problems solved.
