### ISSUE TITLE
Mr. Beast stuck in Japanese mode

### ISSUE THREAD

**Issue by Jokersflame** [yuliskov/SmartTubeNext#2336]
Hello. I have a fan of the YT channel Mr. Beast in my household. Apparently YouTube is offering content creators a chance to have different voice tracks, so Mr. Beast for example can have different languages via voice over. 

Currently on my TV his channel is automatically set to Japanese. Is there anyway to change his voice back to the normal English?

**Comment by toastyjc** [comment]
Yeah, on the video click the quality icon and then select audio formats.

From there you can select the language you're looking for.

Make sure you have an up to date version installed as previously it was impossible to tell what each audio stream was in terms of language
