### ISSUE TITLE
Subscriptions tab is totally blank

### ISSUE THREAD

**Issue by swagbbq** [yuliskov/SmartTubeNext#2377]
Version 17.39
Issue appears on two different devices: Shield TV and Google TV

Subscriptions tab is totally empty when signed in. All other sections have tiles in their grids. Channels section shows that subscribe channels have content. Subscription tab previously filled with content. 

Tried logging out and rebooting devices. 

Attached images of empty Subscription tab and tile-filled Channels tab for reference. 

![A3D2BB28-F58F-4C05-B8F2-3D887653DB8C](https://user-images.githubusercontent.com/26174396/230616283-3cd65b91-6c2d-48df-818b-d412c27904da.jpeg)

![A6183A16-4326-440C-AFB5-636E11163D6F](https://user-images.githubusercontent.com/26174396/230616286-4241d696-3de0-4809-89d3-eaaa3c9f5345.jpeg)

**Comment by Saroumane** [comment]
You are not alone, same here since yesterday (or the day before). Shield TV, latest stable SmartTube

**Comment by swagbbq** [comment]
resolved with v17.61 thanks!

**Comment by r3dsn0wz** [comment]
On 17.98 Channels and Subscriptions are completely empty again
