### ISSUE TITLE
Playback option defaults after update

### ISSUE THREAD

**Issue by Kal250** [yuliskov/SmartTubeNext#2381]
The last approx 4 updates to STN beta  (currently on 17.61) have reverted my default playback option to play videos continuously rather than keeping my previous setting of stop playback after one video.  This jas happened in much earlier builds but was fixed quickly, and now appearing again.  As far as I can tell this is the only option that changes after an update.

**Comment by MrRobot12** [comment]
Can confirm that this is happening to me too on the latest beta version.

**Comment by Salamat-UK** [comment]
Yes, can also confirm.......very annoying!

**Comment by jkr4m3r** [comment]
Came to post about this, can confirm.

**Comment by Wolf68k** [comment]
Not only can I also confirm this is a thing, that shouldn't be, it gets worse.
On my FireTV when I force quit the app and go back in, the setting is again reset to default.

If I double Back button to exit and go back in it is fine, but that's likely because while I might be exiting the app the app is not quitting.

**Comment by jkr4m3r** [comment]
> Not only can I also confirm this is a thing, that shouldn't be, it gets worse. On my FireTV when I force quit the app and go back in, the setting is again reset to default.
> 
> If I double Back button to exit and go back in it is fine, but that's likely because while I might be exiting the app the app is not quitting.

Not the case here on my Shield Pro 2019, it loses the setting no matter how I exit.

**Comment by Kal250** [comment]
This issue continues with beta update 17.62 just updated a few minutes ago.  Persists after reboot or any closure of STN program

**Comment by Kal250** [comment]
Correction not sure if it was a glitch, but after 2nd reboot setting was saved

**Comment by Kal250** [comment]
Setting has persisted and not reset to default consistently over 10x force close of app then app launch, same on 10x normal close/exit then app launch, same behavior on 15x reboot device then restart app, and finally same behavior without reverting to default with 2x power cycle confirmed power off greater than 5minutes each cycle, then power on device start then app start.  Each of these test cycles produced no recurrence of playback default, and retained the last set configuration (varied configurations other than default play videos continuously).  I consider this resolved and shall close the issue.

**Comment by Salamat-UK** [comment]
Yes, no mention of a fix in the last update notes

**Comment by jkr4m3r** [comment]
Fixed on latest beta, I saw a note in the updater within the app. Shield Pro 2019 here, perhaps it is OK on my device because I opened recents and killed it before starting it again? Never used a Firestick, so I'm assuming it has a recents list like unmodified Android does?

**Comment by jkr4m3r** [comment]
> No I get that. But to me I don't think an issue should be closed if the stable still has an issue.

Be thankful that you're getting a great app for free. The world owes you nothing.

**Comment by stevensmedia** [comment]
This is a development tool, not a front line tech support tool. Of course they close the bug when it's fixed upstream.
