### ISSUE TITLE
"Video source isn't working or incorrect time"

### ISSUE THREAD

**Issue by Salamat-UK** [yuliskov/SmartTubeNext#2415]
As of today, have been getting this error popping up again! Leaving the video running, it goes to a black screen and sometimes reloads after a pause. I did have an update, Beta 17.67, today, but was happening before this.

**Comment by IIIPeAceIII** [comment]
Yes, me too can't play any video. 😔

**Comment by Salamat-UK** [comment]
Must loaded 17.68, cleared cache, forced quit, reloaded, but the issue is still there. Vid will load from Subscriptions, play for a short while before buffering then going to black screen, with the message. (Can also confirm vids won’t load from the Home screen!)

**Comment by Salamat-UK** [comment]
My FireTVStick just did a minor update to Fire OS 5.2.9.5 (686800020) and that has possibly solved the issue. Just watched two vids, without any problems. 🤞

**Comment by Salamat-UK** [comment]
Just installed the last Stable, 17.62, and still getting the issue. (I didn’t uninstall 17.68 first, maybe I should have?) Any suggestions?

**Comment by IIIPeAceIII** [comment]
> Just installed the last Stable, 17.62, and still getting the issue. (I didn’t uninstall 17.68 first, maybe I should have?) Any suggestions?

I Installed latest beta version 17.68 & uninstalled stable version and it has resolved the issue but with a bit loading time at the starting of the video. No error message now. ☺️

**Comment by Salamat-UK** [comment]
I decided to uninstall the previous Beta and Stable versions. I then installed 17.68 which was mostly trouble free, though occasionally the message cropped up. Today it upgraded to 17.71 and again, considerably better, but still the occasional ‘glitch’!

**Comment by Salamat-UK** [comment]
Yesterday, decided to reboot my router and this seems to have solved the issue! Have played several videos, over several hours, and have not had one crash. Will therefore close the issue.

**Comment by triksmelb** [comment]
same issue on “Dianna and Roma” videos 
17.95 on Shield Android TV 9.1.1

**Comment by nritech** [comment]
Same issue facing on every video since few days...no fix yet!

**Comment by azizkhmy** [comment]
Just remove data and cache on Android and re-login your youtube account

**Comment by yashbpatel161290** [comment]
Just check the time on whichever device you're using. It must be slightly behind the actual time. I had this issue. Time was somewhat 10-15 seconds behind. I manually updated it and the issue is gone.

**Comment by triksmelb** [comment]
> > Just remove data and cache on Android and re-login your youtube account
> 
> You mean of YouTube app?

no, he means data & cache in Android App settings:

![Screenshot 2023-07-19 at 8 25 21 am](https://github.com/yuliskov/SmartTubeNext/assets/12489962/6b7ebdf6-b1e8-44d4-8d98-677931d3d066)

**Comment by hxii** [comment]
Clearing cache and data doesn’t fix the issue. I’d there a way to debut this?

**Comment by azizkhmy** [comment]
The easy way is to remove your smartube app and re-install back the apps. Re-login youtube account on smart apps. :;

**Comment by EdmundGerber** [comment]
> Could it be because I'm using a pi-hole DNS that blocks lots of YouTube ads?

No, as pihole cannot block youtube ads - they are served from the same domain as the video.
