### ISSUE TITLE
Make a separate build for x86 or x86_64

### ISSUE THREAD

**Issue by hmtheboy154** [yuliskov/SmartTubeNext#2467]
A while ago I made this Pull requests : https://github.com/yuliskov/SmartTubeNext/pull/2407

but it was not merged because the dev said that 
> Hi, this change could drastically increase the size of the final apk file. It's not good.

So can we instead getting apks of each architecture instead of only a single arm apk ? This could help us a lot with x86 hardware. Not to mention in the future some devices will only ship with 64bit support

**Comment by ACR-Jeff** [comment]
That would be great, Even provide instructions on how to compile with the proper drivers would be helpful and better than nothing, STN used to install just fine on x86, Yet then it just stopped after a certain version.

**Comment by hmtheboy154** [comment]
> That would be great, Even provide instructions on how to compile with the proper drivers would be helpful and better than nothing, STN used to install just fine on x86, Yet then it just stopped after a certain version.

it's because the dev only provide arm version of the app now, not even arm64. Because they want the app to be "as lightweight as possible"

**Comment by Xtr126** [comment]
It would also be required to support new 64-bit only Android devices that can't run 32-bit apps at all.

**Comment by hmtheboy154** [comment]
@yuliskov I saw the previous build got x86, but latest one doesn't. What's going on ?

**Comment by hmtheboy154** [comment]
stable build got x86 now, time to close this issue
