### ISSUE TITLE
Hide the like/dislike count

### ISSUE THREAD

**Issue by ClementNerma** [yuliskov/SmartTubeNext#2493]
Hi there!

As much as the new like/dislike count feature is really great for all the people who want that information, I personnally don't care about it when watching videos on my TV, and the use of the thumbs up and down emojis (which are rendered as yellow icons on my Shield TV) are a bit distracting.

Would it be possible to add an option to hide these informations? I didn't find any in the settings (I looked in general, user interface and video player).

Thanks :)

**Comment by hmm-norah** [comment]
The dislikes being an estimate make them unreliable as well as the emojis being distracting.

**Comment by ClementNerma** [comment]
Seems fixed by [this commit](https://github.com/yuliskov/SmartTubeNext/commit/7230e90f3ff9e84e1f4a7aa17d4b7fd7dbf6fc8a). I can't test it right now, but I'll try in the next days.

**Comment by ClementNerma** [comment]
I tested it yesterday and it does work fine, closing this issue :)
