### ISSUE TITLE
Option to hide shorts stays set even when unselected

### ISSUE THREAD

**Issue by Neil-Trotter** [yuliskov/SmartTubeNext#2496]
STN Version is Beta 17.88, running on nVidia Shield.    Experimenting with "General | Misc | Hide Shorts" options, I found that selecting "Hide all shorts" hid content I actually wanted to see on certain channels.  Having unselecting the Hide option, the shorts have not reappeared as listed in Channels.  I have double-checked settings, restarted app, restarted device, etc., but shorts are still missing (that I can see when viewing same channels in desktop browser).  Is this known or intended behaviour?

EDIT:  I think that shorts may not be the only items missing from Channels.  Mysteriously, channels are hilighted in red (signifying a new upload to the channel), but often no new upload is seen in the main panel for the channel on the right, even if it had earlier been offered in the Home random selection.

Just heads-up/feedback.

Thanks for all the excellent work on YTN!

Best wishes,
Neil

**Comment by NTICompass** [comment]
This seems to be the same issue/feature request I posted in #2491

**Comment by Neil-Trotter** [comment]
It seems that way!  Definitely some odd behaviour in the past few days, and from what you say my noodling with "Hide" options may be irrelevant.  Anyway, just wanted to raise a flag rather than sit on my sofa wronging hands :-)

**Comment by Neil-Trotter** [comment]
Only after reading Eric's (NTICompass) comment in the link he provided above did I become aware of the "long-click" functionality that enables opening the channel from the Channels section.  This provides me a workaround that I can live with, thus I will close as an issue.  Nonetheless I think I prefer the previous functionality, where a simple click on the channel from the Channels section listed all types of content from a channel in descending chronological order.
