### ISSUE TITLE
Channels no longer have named video sections

### ISSUE THREAD

**Issue by ZenOrion** [yuliskov/SmartTubeNext#2508]
Not sure if this is the right term for it, but on both 17.88 Stable and 17.91 Beta there are no named sections for videos on someone's channel. Normally you would see different rows of videos the channel uploader grouped together, like "Popular Uploads", favorites, videos in a series, etc., but now there are no names telling you what each row of videos are grouped under. You can just go down a persons channel and see row after row of random videos with no way to know what they're categorized under. I don't think it was like this a day or two ago. I'm currently using an Amazon Fire TV Stick, Fire OS 7.6.3.3.

**Comment by Keiyuu** [comment]
Same problem here, on Android TV (Sony).
And not only that, but usually the top row on a channel always displayed the latest videos sorted by date. Now it shows random old stuff there, which makes it really difficulty to find recent videos of a channel.

**Comment by ZenOrion** [comment]
Seems like the update 17.95 for both Stable and Beta fixed the issue. I'll close this for now.
