### ISSUE TITLE
Random Playback Mode

### ISSUE THREAD

**Issue by DTK21** [yuliskov/SmartTubeNext#2542]
So as the recent update for the beta app there's a Playback Mode which at first seems cool but takes away the randomness of the next video due to any video within a tab becomes a playlist

For example, before I could search a video play it and have the next video be random. But now if I click that same video the ones list after that would play. Same goes for the history videos, select a video then the history tab acts as a playlist instead of playing the selected video then something random after.

I know playback mode is tied to the icon where shuffle and etc is but maybe include a random playback setting icon for the way the app used to play next videos randomly as it used to be as to not remove what could be useful to others

**Comment by weicor** [comment]
did you find solution to this ?

**Comment by DTK21** [comment]
Nah I just use an out of date version from the stable build, but it's as far back as before showing comments were a thing so I don't know the latest version that didn't have the Playback Mode setting

**Comment by DTK21** [comment]
Ok so I figured it out, go into Video Player settings, then misc, then uncheck "use current section contents as a playlist".
Guessing this was also added in along with the playback modes but it works exactly how the app used to and not playing everything like a playlist whether that was the subscription tab, home tabs, searched videos, etc
