### ISSUE TITLE
Latest update (18.05) only plays 'Live' stream videos

### ISSUE THREAD

**Issue by Tickleusknee** [yuliskov/SmartTubeNext#2566]
Previously working without issue - no settings since changed.
Update 18.05 will not play any video. Live stream videos do seem to work, however.
Have clean reinstalled from downloaded beta apk. Same issue, both with and without backup settings applied.

**Comment by doug8888** [comment]
Same here, worked OK after installing update but not working after a reboot.

**Comment by Tickleusknee** [comment]
Fixed - 18.09.
Thanks
