### ISSUE TITLE
[BUG] Persistent video playback errors, all versions

### ISSUE THREAD

**Issue by tomekwwa** [yuliskov/SmartTubeNext#2587]
For the past two or three days, there is a message on every video that the source is unavailable or at the wrong time.  The video pauses for a few seconds and then comes back on and then does the same thing again after a while.  Version 18.12, but in earlier versions too.

**Comment by triksmelb** [comment]
If you mean “video source isn't working or incorrect time” error - I’m having the same issue on v17.95 running on Shield Android TV 9.1.1 on many of  “Diana and Roma” videos as an example.

**Comment by tomekwwa** [comment]
Exactly "video source isn't working or incorrect time".

**Comment by triksmelb** [comment]
seems to me the error occurs only on some videos. 

Definitely get it on [Diana and Roma](https://www.youtube.com/@KidsDianaShow) videos but NOT on these [Car Review](https://www.youtube.com/channel/UCsqjHFMB_JYTaEnf_vmTNqg) videos.

**Comment by tomekwwa** [comment]
I'm getting it on almost all videos and there are problems with updating app, there is an error displayed all the time.

**Comment by tomekwwa** [comment]
It's still the same on 18.15. Also on 18.12, 18.09 and on stable 17.95. 2 android tv and on 1 tv box. I changed internet source, dnses and it is still the same. HELP!
This is how it works: [STN playback errors](https://youtu.be/7pcVqOcVjNU)

**Comment by ErvinMark** [comment]
I have same issue from today ,won't open any video on the app ,just keep showing loading !

**Comment by ErvinMark** [comment]
Well for me fixed after an firetv cube update ,seems like the issue is with Amazon devices,after update everything is working fine now ,so I suggest to update your device ,also check if twitch is doing same thing if it is is your device!

**Comment by tomekwwa** [comment]
> Well for me fixed after an firetv cube update ,seems like the issue is with Amazon devices,after update everything is working fine now ,so I suggest to update your device ,also check if twitch is doing same thing if it is ,is your device! So it's nothing to do with the app.

For now the only solution for me was to buy YT Premium. It works well. STN still shows only errors...

**Comment by triksmelb** [comment]
There was an update this morning, so I did it but even before that haven’t seen the issue last couple of days (2017 Shield).

**Comment by kingozone** [comment]
> Deleting the app's data fixes the issue. You'll have to redo all settings. After finished, use the app's settings-backup feature for the next time this happens.

This did not work for me. Even uninstalling and reinstalling hasn't worked on my Chromecast with Google TV.

**Comment by tomekwwa** [comment]
I have 3 different internet sources: fiberoptic and two LTE, 3 different routers and it is all the same. And YT Premium 4K works all the time without any problems, so the problem is in the STN!

**Comment by josejoa** [comment]
> 
Then you are right. It seems that in the 17.67 beta the author tried to fix this error but without success, let's jope he finally can fix it.

**Comment by josejoa** [comment]
> I have 3 different internet sources: fiberoptic and two LTE, 3 different routers and it is all the same. And YT Premium 4K works all the time without any problems, so the problem is in the STN!

Then you are right. It seems that in the 17.67 beta the author tried to fix this error but without success, let's jope he finally can fix it.

**Comment by v2cn** [comment]
I have same issue too for a couple times.

**Comment by josejoa** [comment]
> I have same issue too for a couple times.

In the 18.22 Beta the author tries again to fix this error. I will wait until the stable version, let's hope this time he hits this issue:

[18.22 Beta](https://github.com/yuliskov/SmartTubeNext/releases/tag/18.22) Pre-release
The possible fix for the video source error
The beta icon color changed to red

**Comment by tomekwwa** [comment]
Great news, i will test it this afternoon.

**Comment by samleemc** [comment]
I am on 18.15 on a Sony google TV. Similar issue, however, the app can't even show video list in the home page.

Tried reinstall, doesn't work either.

**Comment by tomekwwa** [comment]
For me 18.23 work like it should be. No errors. Great thanks to @yuliskov
