### ISSUE TITLE
Still not solved the video source error

### ISSUE THREAD

**Issue by josejoa** [yuliskov/SmartTubeNext#2637]
It continues appearing the alert "The video source isn't working or incorrect time", and sometimes appears a new one "Loadsuggestions error: fromNullableresult is null", I have the last 18.27 stable version.

**Comment by josejoa** [comment]
> yes same with me,still not fixed

I think the author attacks again the issue in his last version [18.28](https://github.com/yuliskov/SmartTubeNext/releases/tag/18.28s)

**Comment by josejoa** [comment]
> > > yes same with me,still not fixed
> > 
> > 
> > I think the author attacks again the issue in his last version [18.28](https://github.com/yuliskov/SmartTubeNext/releases/tag/18.28s)
> 
> its fixed now?

Until the moment none error, take care..

**Comment by tomekwwa** [comment]
For me 18.23 works great, but 18.28 is showing video source error all the time.

**Comment by josejoa** [comment]
> For me 18.23 works great, but 18.28 is showing video source error all the time.

The author attacked this error in the last version (18.28), I think this is a problem with the buffer. In the 18.23 version I still had the problem, with the last version still I don't have any error. And I saw many videos, but I will continue checking out.

**Comment by josejoa** [comment]
Another possible fix for the buffering issue with the 18.38 Beta :-))

**Comment by josejoa** [comment]
> I have this same issue on various videos on the latest beta update as of date of this post

I think the author is working on it, "the buffering issue", but I think he has some problems and still he couldn't address correctly this issue, let's hope some day he strikes in the key. For the moment we only can wait...

**Comment by Bucko-m** [comment]
Still happens for me on my Sony Bravia android tv hope it gets resolves soon. Seems to happen on longer videos. I'm using the stable version.

**Comment by josejoa** [comment]
> Still happens for me on my Sony Bravia android tv hope it gets resolved soon. Seems to happen on longer videos. I'm using the stable version.

I think that with the latest stable version (18.50) it is solved. Until now none error, I will continue checking nevertheless...

**Comment by josejoa** [comment]
First error after many videos. Not solved but with so few errors I think is not bad, besides the error disappears promptly. I think the author has improved a lot this issue, at the beginning the error appeared continuously.

**Comment by marcopedone** [comment]
On my Sony Bravia android TV happens continuously (almost every video and sometimes multiple times per video), it fixes itself after a long while (30 sec to several minutes), especially when on ethernet, or never comes back to normal, and then I have to go and manually remove and reconnect the ethernet cable to fix it.

**Comment by josejoa** [comment]
> On my Sony Bravia android TV happens continuously (almost every video and sometimes multiple times per video), it fixes itself after a long while (30 sec to several minutes), especially when on ethernet, or never comes back to normal, and then I have to go and manually remove and reconnect the ethernet cable to fix it.

In my TD Systems Android TV, it happens mostly in long videos and fixes itself after 5 to 20 seconds maximum, always on wifi 2.4 Ghz.

**Comment by josejoa** [comment]
Another possible fix of the "source error" is taken in the 18.65 Beta...

**Comment by josejoa** [comment]
I think I get rid with this error after amplifying the signal of the WIFI through the settings of the router, cheers!

**Comment by josejoa** [comment]
I close this issue, for me is solved. Cheers!

**Comment by josejoa** [comment]
I close this issue, for me is solved. Cheers!

**Comment by ACR-Jeff** [comment]
Version 18.92 I have gotten the error "Loadsuggestions error: from Nullable result is null" along with a new one stating I am not signed in after receiving that error until a restart of my device.
