### ISSUE TITLE
18.27 automatically exits app

### ISSUE THREAD

**Issue by sinkrate1** [yuliskov/SmartTubeNext#2638]
Hello, I recently updated to 18.27 and use SmartTube almost every night to play a white noise video through the TV. This helps considerably while working third shift. About 2-3 days ago, I I'd wake up and began to notice my FireStick would be at the home screen exactly 4 hours into my usual white noise video. This has been consistent over the last 2-3 days while I'm sleeping after work.

I've been using SmartTube for almost a year and haven't had this happen until the most recent update. 

Is this a bug, or new code in the app?

Thanks!

**Comment by Jinxy93** [comment]
been having this same issue after the most recent few updates. can't find any new settings or anything to disable it so assumed it was a bug.

**Comment by sinkrate1** [comment]
> been having this same issue after the most recent few updates. can't find any new settings or anything to disable it so assumed it was a bug.
> 
> videos will play for anywhere between 30 minutes to 3 hours before just exiting to the home screen. the app doesn't close, its still open in the background, and when reopening the app it pulls the video back up.

I just had the YouTube app do this to me, it sounds like a FireStick software issue. Oh jeez.

**Comment by sinkrate1** [comment]
Go to your FireStick settings > Preferences > Data Usage Monitoring > Still Watching turn off
