### ISSUE TITLE
Wrong fallback decoding

### ISSUE THREAD

**Issue by ekoprihastomo** [yuliskov/SmartTubeNext#2790]
I have AV1 capable hardware and there's no problem at all playing/decoding AV1 video
The problem is if I set my preset to AV1 and AV1 is not available for the video I currently watch, SmartTubeNext will fallback to AVC, not to VP9
The order should be AV1 -> VP9 -> AVC right?

**Comment by Mister-XY** [comment]
Same here.

**Comment by ekoprihastomo** [comment]
Updated to version 19.15
With the latest version I've watched several videos to test, if AV1 is not available it correctly fallback to VP9 now 💯
