### ISSUE TITLE
Stuck in fast forward.

### ISSUE THREAD

**Issue by BeefBaby** [yuliskov/SmartTubeNext#2844]
Everything worked fine, then out of no where every video I play is fast forwarding like it's in 10x speed, no audio. 

Video speed isn't toggled. I even reinstalled, and tried using the beta. Same issue.

**Comment by BeefBaby** [comment]
Seems to be related to Bluetooth audio.

**Comment by MCGamerGuy06** [comment]
How did you fix it?

**Comment by BeefBaby** [comment]
> How did you fix it?

I believe I just unpaired and repaired by Bluetooth headphones, and restarted the application/device. Hasn't happened since.
