### ISSUE TITLE
Ability to stream YouTube vids with Google Cast

### ISSUE THREAD

**Issue by anon238** [yuliskov/SmartTubeNext#285]
Then I can ditch the default YouTube app for casting.

**Comment by sciencebug** [comment]
same as #232

**Comment by foreveryoungforty** [comment]
@anon238 function made available in new version 10.75 - please close this issue - thanks.

**Comment by anon238** [comment]
> @anon238 function made available in new version 10.75 - please close this issue - thanks.

Thank you very much. I will download this version later. 🚀

**Comment by mmortal03** [comment]
I just tested 10.76 by trying to cast a YouTube video from Chrome to it, and it opens up SmartTubeNext, but then just stays on the SmartTubeNext main screen and doesn't load the video or anything.
