### ISSUE TITLE
User Search History

### ISSUE THREAD

**Issue by zuul47** [yuliskov/SmartTubeNext#2897]
Underneath the search bar it now shows popular trending searches and not my own searches. This started happening today.
Device: FireStick 4k
Version: 19.17 Stable and 16.39

**Comment by EdmundGerber** [comment]
I'm seeing the exact same thing. Long pressing on one of those, and choosing 'clear search history' does nothing useful. They clear, then are back the next time I search.

**Comment by ZandigSlaytanic** [comment]
Same here on Nvidia Shield Pro. Noticed it starting yesterday.

**Comment by Hexinator1302** [comment]
I have the same problem since today. 

Device: Beelink GT King II

SmartTube Version: beta 19.39

**Comment by EdmundGerber** [comment]
I tried downgrading to 19.33 to see if any change - same behaviour. It's possible this is something youtube might be foisting on us. I hope it can go back to the way it was, though.

**Comment by Linden10** [comment]
Just started happening to me too now, my past search history being replaced with current trends!

On the ios youtube though my search history is still there so something on youtube’s end must of changed.

Hope a solution can be found or this is only a temporary problem!

**Comment by NoOneReally2021** [comment]
Same problem, noticed yesterday, downgrading didn't make difference even with clean reinstall

**Comment by zuul47** [comment]
Update: Dev is aware of the issue and is trying to resolve it.

**Comment by huhwhatwho** [comment]
It is a sad world if there are that many people searching for the s**t that is showing up.  Is that really what is trending?

**Comment by reyzor-q** [comment]
Same problem here.

**Comment by zuul47** [comment]
It looks like in the new 19.42 Beta this was able to be solved. Going to download it in a few minutes.

**Comment by zuul47** [comment]
My recent searches now show up with the beta version

**Comment by EdmundGerber** [comment]
> It looks like in the new 19.42 Beta this was able to be solved. Going to download it in a few minutes.

And a nice new setting to disable showing popular search results, going forward.

**Comment by DiscoFever78** [comment]
Yeah, I need *my* searches, not trending searches :) ...Is there an easy way to upgrade to 19.42 Beta from within SmartTubeNext?

**Comment by reyzor-q** [comment]
Thanks @zuul47, my searches in the app are now showing up but there's an issue where searches on my phones youtube app is not syncing across to Smarttubenext. This wasn't the case previously.

**Comment by zuul47** [comment]
> Thanks @zuul47, my searches in the app are now showing up but there's an issue where searches on my phones youtube app is not syncing across to Smarttubenext. This wasn't the case previously. 

Yea he mentioned that there's a sync problem. Could be something on YTs side.

**Comment by zuul47** [comment]
> Yeah, I need *my* searches, not trending searches :) ...Is there an easy way to upgrade to 19.42 Beta from within SmartTubeNext? 

I don't think so. I had to delete my Stable version and install the Beta.

**Comment by DiscoFever78** [comment]
Wonder if there's a scheduled release date for the Beta to switch to Stable status? Just curious :)

**Comment by zuul47** [comment]
> Wonder if there's a scheduled release date for the Beta to switch to Stable status? Just curious :) 

Based on his previous Stable releases it's looking like monthly around mid month.

**Comment by Hexinator1302** [comment]
I have the current beta on it. Unfortunately, the search history is still not synced with the official YouTube app.

**Comment by crackers8199** [comment]
this doesn't seem fixed, especially not in the most recent stable release. now i get no search history showing up...not my own nor trending. nothing shows until i type something.

**Comment by shadowscott** [comment]
What is the setting to enable my searches?
