### ISSUE TITLE
[Feature request] Add option to not show media keys when doing fast forward/rewind 

### ISSUE THREAD

**Issue by extricator** [yuliskov/SmartTubeNext#3]
Add option to not show media keys when doing fast forward/rewind in the video player screen.

**Comment by aouni84** [comment]
I like the new interface! I'm glad to know a new project has started.

I'd also like to see a setting page to control stuff like media keys etc..

**Comment by steve51184** [comment]
Yeah the setting page is what's gonna make this app 100x better than it already is.. I can't wait!
