### ISSUE TITLE
Feature request - add a 5-10 sec pause before automatically start a next video

### ISSUE THREAD

**Issue by gamestheory** [yuliskov/SmartTubeNext#307]
hello!
it would be nice to a have a small pause after current video finished to select whether start suggested one or not, like its done in original client
thanks in advance

**Comment by foreveryoungforty** [comment]
Hello, function already exists, see button 4 in upper row of player ui, you have options there, pauze after current video is one of them.

**Comment by gamestheory** [comment]
oh, many thanks @foreveryoungforty for pointing that out ! :)
