### ISSUE TITLE
request:add to turn off autoplay

### ISSUE THREAD

**Issue by ScottMccay** [yuliskov/SmartTubeNext#311]
please make it possible to turn off autoplay

**Comment by foreveryoungforty** [comment]
Hello, function already exists, see button 4 in upper row of player ui, you have options there : pauze or even stop after current video are two of the four possibilties.

**Comment by aecarvalho** [comment]
Pl

> please make it possible to turn off autoplay

Please close the issue as it has been resolved, disabling autoplay is already there in the pause/play UI as @foreveryoungforty mentioned.
