### ISSUE TITLE
Feature request - Casting

### ISSUE THREAD

**Issue by flappy81** [yuliskov/SmartTubeNext#33]
Like on the original project, it would be nice to have the casting option enabled. Other than that this is my new favorite YT app. Awesome work.

**Comment by ManuLinares** [comment]
The feature was in the old code, so I assume it will be added to this new project

**Comment by Petahh** [comment]
+1

**Comment by samschafer** [comment]
Would love to see it work with YouTube Vanced casting so I don't need both apps.

**Comment by foreveryoungforty** [comment]
@flappy81 function made available in new version 10.75 - please close this issue - thanks.
