### ISSUE TITLE
Nvidia Shield on LG CX HDR Issues

### ISSUE THREAD

**Issue by JasonKAls** [yuliskov/SmartTubeNext#367]
Is HDR supported on the Nvidia Shield Pro? It seems to not play videos in HDR mode.  I'm currently on 10.77.

**Comment by gfrancesco** [comment]
Same problem for me, LG CX, Nvidia Shield (2017), last beta 10.78.
The video does not start, black screen.
Same video on the official YT app on the Shield plays in HDR with no problems.

(Love SmartTubeNext btw, such a nice work!)

**Comment by wjhrdy** [comment]
This is a well-documented hardware limitation of even the most recent 2019 Shield TV Pro.

Here is NVidia talking about it on their forum 1 year ago:
https://www.nvidia.com/en-us/geforce/forums/shield-tv/9/324929/why-no-vp9-profile-2-in-new-shield/2301821/

**Comment by gfrancesco** [comment]
How is the official Youtube app then does it without hardware support?

**Comment by gfrancesco** [comment]
Videos play after selecting ***vp9*** as opposed to ***vp9+hdr*** in _Settings -> Video Player -> Video Preset_.
Of course not in HDR, but at least you can watch them (in 4K).

**Comment by JasonKAls** [comment]
apologies, I see that this is a Shield issue and not yours.  Closing this issue. Thanks!
