### ISSUE TITLE
User Code is loading...

### ISSUE THREAD

**Issue by anubis-genix** [yuliskov/SmartTubeNext#4]
User Code is not shown to sign-in on FireTV 4K
![20201015_220514](https://user-images.githubusercontent.com/40500650/96180308-86d7c080-0f32-11eb-953b-a988bd629d75.jpg)

**Comment by anubis-genix** [comment]
found the issue in my pi-hole setup. i assumed there was a bug in STN since i was able to get a code in SYTTV.

**Comment by zhucemax** [comment]
Sometimes， if your IP have to do the recaptcha，you will get this page .
