### ISSUE TITLE
No audio when casting from android phone to SmartTubeNext

### ISSUE THREAD

**Issue by anphucnguyen** [yuliskov/SmartTubeNext#406]
How to reproduce:
1. Connect MiBox S to Monitor (or TV)
2. Casting video from phone to SmartTubeNext on Mibox
3. Turn off  Monitor (or TV), does not unplug.

Expectation result:
- Video can be played with audio.

Actual result:
- After playing 10~20 mins, the video continues play but no audio. 

Information:
- Device: Mibox S 4K 2020
- SmartTubeNext: v10.81
- Phone: Youtube Vanced v16.02.35

**Comment by finnzz** [comment]
I have the same setup:
SmartTube Next v10.81
Vanced v16.02.35
MiBox S 4k, Android 9.0

I have been using v10.81 for a couple hours.  I cast 2 40min videos and didn't have any audio drop out.  I hadn't experienced that problem in previous versions of SmartTubeNext either.

I know it doesn't help you directly, but might be good to know while troubleshooting.

**Comment by anphucnguyen** [comment]
Thanks @finnzz.

I rolled back both SmartTubeNext and Vanced to older version (v10.77 and v15.43.32), the issue is solved. Have no idea it's the bug either SmartTube Next or Vanced.

**Comment by foreveryoungforty** [comment]
Combination SmartTube Next v10.82 on Sony Android TV and Vanced v16.02.35 works OK here.

**Comment by anphucnguyen** [comment]
> Combination SmartTube Next v10.82 on Sony Android TV and Vanced v16.02.35 on tablet works OK here.

Did you follow this step "Turn off Monitor (or TV), does not unplug"?
If I keep TV turning on, this issue is not happened.

**Comment by anphucnguyen** [comment]
Try the latest version: v10.127, the issue doesn't happen.
So, I closed ticket
