### ISSUE TITLE
[Feature Request] Option to disable Play Next Video

### ISSUE THREAD

**Issue by ACR-Jeff** [yuliskov/SmartTubeNext#431]
I searched high and low in the settings for this option yet have been Unable to locate.
Can you please add an option to disable playing the next video?
Thank you for all you are doing with this. Enjoying it daily.

**Comment by foreveryoungforty** [comment]
Hi, it's in the player functions, upper row, 4th icon, several options, among which Stop playback after one video. Please close issue if this is ok. Best regards.

**Comment by ACR-Jeff** [comment]
> Hi, it's in the player functions, upper row, 4th icon, several options, among which Stop playback after one video. Please close issue if this is ok. Best regards.

Oh duh me. Now I feel silly. Thank you
