### ISSUE TITLE
With device screen off, autoplay next video turns screen back on.

### ISSUE THREAD

**Issue by sasotepina** [yuliskov/SmartTubeNext#470]
(using on android tv)
I have a video playing and I turn the screen off (Android TV: Eco settings, screen off). When the next video starts playing, it turns the screen on again.
I'm not sure if this started with one of the latest updates or was it always like that.

**Comment by foreveryoungforty** [comment]
I think this has to do with the network/wifi settings of your android tv. On my sony, i have options there like "remote start", "remote control", ”IP control"..... with those functions ”on”, i have the same as you describe, as those functions are intended to do so. Hope this helps.

**Comment by sasotepina** [comment]
I found an older APK.
Version 10.88 still works fine (screen stays off). So the issue started with some version after ver. 10.88.

**Comment by foreveryoungforty** [comment]
Strange, i just followed the sequence of actions you described in your first message with version 10.96, and here the screen remains off...

**Comment by sasotepina** [comment]
I tried it on a second TV. Same behaviour. Both Philips, one is Lollipop 5.1.1, the other one is Oreo 8.0.0.
I don't have any other brands to test on.

**Comment by foreveryoungforty** [comment]
I have Sony on android 9.

**Comment by sasotepina** [comment]
With version 10.119 it works fine again.
