### ISSUE TITLE
Add a "Add to Watch later" menu item to long-press menu

### ISSUE THREAD

**Issue by Soitora** [yuliskov/SmartTubeNext#473]
Hey, when going through my Subscription for the night and wanting to add which videos to watch I use the "Watch later" feature (built-in playlist).

Right now you need to do the following in the app to do so:
> Long-press and item, go to "Add to playlist", press the "Watch later" playlist, then press Return button two times

That's about 5-6 presses.

My idea is similiar to the actual YouTube app itself, under the "Add to Playlist" button in the long-press menu, add a button that says "Add to Watch later" and have it close after press. This makes the process much faster.

This is how it looks like in the YouTube app:
![image](https://user-images.githubusercontent.com/10836780/107897830-77956d80-6f3a-11eb-969a-a055026ff8f5.png)

Thanks

**Comment by jdahdah** [comment]
+1, but I would prefer it to be the first item on the list. It seems like saving something for later while browsing the video suggestions is a more common task than adding a video to a specific playlist.

**Comment by Soitora** [comment]
> +1, but I would prefer it to be the first item on the list. It seems like saving something for later while browsing the video suggestions is a more common task than adding a video to a specific playlist.

I could agree with this 👍🏻

**Comment by Soitora** [comment]
Seems to have been added in 39e805764c32f0f05784495be6747e3b46815ad7, @jdahdah
Although some users are disliking it in #1007, it is absolutely amazing
