### ISSUE TITLE
Disable AutoPlay

### ISSUE THREAD

**Issue by Vinny1967** [yuliskov/SmartTubeNext#484]
Would it be possible to disable playing the next video automatically ?.

**Comment by foreveryoungforty** [comment]
You can use the 4th icon in player ui row above, push until stop after each video , blue arrows with diagonal line. After this is set, no more auto-play.

**Comment by Vinny1967** [comment]
Thank you.It would be nice if it went back to the UI after the video stops,but this will help a lot.
Cheers

**Comment by foreveryoungforty** [comment]
Maybe for that, you can choose pause after each video - I use that a lot.

**Comment by Vinny1967** [comment]
Ah yes.That's what I was looking for.Thanks for the assistance.Much appreciated .

**Comment by foreveryoungforty** [comment]
My pleasure to help :-) can you close issue if problem solved. Thanks.
