### ISSUE TITLE
"Repeat current video" plays only twice following with permanent loading circle-sign.

### ISSUE THREAD

**Issue by iG8R** [yuliskov/SmartTubeNext#486]
"Repeat current video" plays only twice following with permanent loading circle-sign.

**Comment by foreveryoungforty** [comment]
Strange, just tested this here with version 10.100, and repeat current video works great... already 6 times andno loading trouble.

**Comment by iG8R** [comment]
Hm, it's weird. Also 10.100 version.
For instance - [https://www.youtube.com/watch?v=TuADbqZIuRo](https://www.youtube.com/watch?v=TuADbqZIuRo)
Here is screenshot.
<details>
<summary>Screenshot</summary>
<img width="1270" alt="SmartTube-RepeatCurrentVideo-02-2021-02-21_161102" src="https://user-images.githubusercontent.com/11407417/108627857-506dfd00-7460-11eb-9218-2b7ebefe20d9.png">
</details>

**Comment by foreveryoungforty** [comment]
Just tested your video, and no problems with repeat here...
Loading problems are mostly related to (temporary) issues with servers/connection/internet provider which vary from country to country, and thus not an issue of the app.

**Comment by iG8R** [comment]
Thank you for your help.
I have 1Gb internet and Mikrotik router, on my PC youtube repeat playback works fine.
Is there any way that I could see the log and figure out what happens while SmartTubeNext's "Repeat current video" broke playing repeated video?
PS. I noticed that if after beginning new video I immediately rewind it to the end the same situation occurs - the video doesn't repeat and shows me increasing time in the lower right corner as it displayed on the screenshot.

**Comment by foreveryoungforty** [comment]
I also did the rewind and fast forward test over here, again no problem here.
I advise you to uninstall the app and do a fresh install of the 10.100 apk, and see if that helps.

**Comment by iG8R** [comment]
I uninstalled, previously purged cache and data, after this I again installed SmartTubeNext 10.100_240 but still the same - "repeat current video" doesn't work as it implies :(
Does SmartTubeNext have some debug log option?

**Comment by foreveryoungforty** [comment]
Very strange as same version works perfect here regarding repeat.
This is an issue for developer.... best provide Android tv device specifications, android version,...

**Comment by iG8R** [comment]
Thank you for your concern :)
My device - Beelink GS-King X on [[ROM] Beelink GS-King X & GT-King Pro ALVATECH Standard Android (9.0 Pie)](https://forum.freaktab.com/forum/tv-player-support/amlogic-based-tv-players/s922x/others-s922x/firmware-roms-tools-dq/787817-rom-beelink-gs-king-x-gt-king-pro-alvatech-standard-android-9-0-pie)

**Comment by foreveryoungforty** [comment]
Just a personal reflection, as i am not that highly technical guy.... i see you run it on a tv box. As you can read on the site, this app is primarly developed for android tv, this means installed and run on the android tv itself (some people even post issues here running it on tablets and smartphones....). I have no experience with tv boxes over here (i run SmartTubeNext right on a Sony android tv, android 9). Maybe some functions are less performant on tv box, i don't know.
Can you maybe tell (as extra info for developer0 which most version version of SmartTubeNext did not have the repeat-issue ?

**Comment by iG8R** [comment]
AFAIK there are no differences between Android on TV-boxes or on TV with Android.
Unfortunately every SmartTubeNext has this issue in my case :( That's why I'd like to see debug log file.

**Comment by foreveryoungforty** [comment]
The log used to be in SYTV as optional function, not yet found in smarttube.
Well, i always look at similarities and differences.
If we compare our situations, same android version 9, same app version, both high speed connections.... the difference lies in device and/or country servers, so my logic tells me the origin must be found there....
Just an idea : have you tried and tested the repeat with other buffer settings ?

**Comment by iG8R** [comment]
Thank you for helping me trying to resolve this issue :)

> Just an idea : have you tried and tested the repeat with other buffer settings ?
It was the first thing that I did when I stumbled upon this issue.
Also I've tried to change all other options regarding embedded player - nothing helped me.

IMHO, to solve this issue it needs:
1. to be a developer who can understand why this function doesn't operate how it's implied only after video was played twice
2. debug log files

**Comment by foreveryoungforty** [comment]
@yuliskov Hi Yuriy, strange issue, as with me this works perfect.... we tried and searched a lot.... If you got the time, can you look into this please ? Thanks, Rik

**Comment by yuliskov** [comment]
This issue will be fixed soon.

Regards, Yuriy

**Comment by foreveryoungforty** [comment]
@iG8R i see code was changed regarding "repeat one", can you  check 10.104 on your tv box ?

**Comment by iG8R** [comment]
@yuliskov @foreveryoungforty Thank you very much :) Now it works like a charm.
