### ISSUE TITLE
[Bug] Casting: video added to queue plays instantly

### ISSUE THREAD

**Issue by finnzz** [yuliskov/SmartTubeNext#502]
When casting to SmartTubeNext, if I add a video to my queue, the video plays right away, rather than after the current video finishes playing.

This only happens if there aren't any videos already in the queue. 

Example 1) Video is playing, queue is empty, and I add a video to queue. The queued video starts playing immediately.

Example 2) Video is playing, and there is a video already queued to play next, and I add a video to queue. The current video continues to play, and proceeds through the queue correctly. 

This started happening many releases ago, but I'm reporting it now just in case the developers aren't already aware of the bug.

SmartTubeNext 10.119 (updated)
FireTV Cube 2nd gen + MiBoxS
Youtube Vanced 16.02.35

**Comment by xerogabe106** [comment]
I'm was having the same issue. Wasn't able to find a way around it.

**Comment by finnzz** [comment]
I think this issue may have been taken care of in 10.124 with the casting fix.  I haven't been able to reproduce the problem since updating. 

I'll close this out later today after I've tested a little more

**Comment by finnzz** [comment]
After more testing, appears to be fixed in 10.124
