### ISSUE TITLE
Casting from iPhone to SmartTubeNext does not work

### ISSUE THREAD

**Issue by inseltraeumer** [yuliskov/SmartTubeNext#504]
The SmartTube app has been linked to the YouTube app on my iPhone 8 (iOS 14.4) via TV code, and it says connected on the phone, though the blue connecting animation is still there. Playback won't start on the Fire TV/SmartTube app. 

If there's anything I can provide to help with this, let me know. Great app, by the way 😊 

Screenshot:
![image](https://user-images.githubusercontent.com/20142443/110247211-5f2dd700-7f6b-11eb-8c5c-76d31a597026.png)

**Comment by finnzz** [comment]
Have you tried clearing the storage on SmartTubeNext, or even uninstalling / reinstalling SmartTubeNext?

I say this because I also saw the same behavior after updating SmartTubeNext.  But after installing/ reinstalling SmartTubeNext and relinking my phone casting worked again

**Comment by inseltraeumer** [comment]
I reinstalled SmartTube and also, for good measure, YouTube on my phone. And it works now!

Thank you!

**Comment by foreveryoungforty** [comment]
Just tested, he linking/casting-function is broken in 10.122 (@yuliskov )

**Comment by yuliskov** [comment]
Seems the casting is broken across all versions on STN now.
Trying to figure out the issue.

**Comment by foreveryoungforty** [comment]
Good fix, casting/linking works again in update 10.124.

**Comment by foreveryoungforty** [comment]
@inseltraeumer please close issue, as casting works again.
