### ISSUE TITLE
The progress bar mouse could not click fast forward

### ISSUE THREAD

**Issue by kai456789** [yuliskov/SmartTubeNext#513]
The progress bar mouse could not click fast forward

**Comment by Australian-Infomaniac** [comment]
Yes, I can't use the mouse to jump forward and back in the video.
I'd like to be able to touch the mouse onto a time-point ahead (or behind) of where I am (for example, to jump to the middle of the video).
This is what I'm used to when I use the computer or my phone.

Thanks for your great work!
