### ISSUE TITLE
Logged in accounts act like they are not logged in

### ISSUE THREAD

**Issue by edgan** [yuliskov/SmartTubeNext#514]
Two different YouTube accounts show the same content as not being logged in. I tried switching accounts. I also tried clearing data and then logging in again. The login page says "User Code is loading...". I tried downgrading with no effect.

Both accounts look normal in the normal YouTube app, and the old Smart YouTube TV app.

Device:
Nvidia Shield

Tested versions:
10.126
10.124
10.84

**Comment by tgt26** [comment]
Same thing started happening to me on Android TV. 
I'm not sure if it was caused by a Google App update I installed from the Play Store.

**Comment by Wampukas** [comment]
The same.

**Comment by strykerx** [comment]
I have the same issue. Reboot, and clearing data doesn't fix it.

**Comment by edgan** [comment]
He fixed it with a new build, 0.127.
