### ISSUE TITLE
Icon label on Chromecast with Google TV no longer fits on one line

### ISSUE THREAD

**Issue by kikura** [yuliskov/SmartTubeNext#517]
![16159786646172917407201050550067](https://user-images.githubusercontent.com/37535682/111457088-ac4e3d80-870f-11eb-8a87-c11be4685dd1.jpg)

See image. Does not effect functionality but cosmetically is annoying.

Thanks.

**Comment by Vogeluff** [comment]
well thats basically just due to googles interface. maybe there are interface settings there? i assume its the same for all apps with longer names..

**Comment by kikura** [comment]
Well it is down to Google as they recently made the icons smaller and that's when the issue appeared. However there are no options withing Google TV to change this.

**Comment by kikura** [comment]
This issue is no longer a problem as Google seem to have reverted to the larger icons again.
