### ISSUE TITLE
Bridhe

### ISSUE THREAD

**Issue by kxd2000** [yuliskov/SmartTubeNext#546]
Is there a bridge app I could use on my firestick for SmartTubeNext similar to the SmartYoutubeNext bridge app? If so, where do I get it from?

**Comment by finnzz** [comment]
https://github.com/yuliskov/SmartTubeNext/issues/505

**Comment by kxd2000** [comment]
Thank you, but when i try to cast from my phone to firestick, it says that the youtube app is not installed on firestick, despite bridge app being installed. What would be the steps to make that work. Assuming no apps installed, having apl for bridge and apk for smarttubenext. What order do I install things or will it even work?

**Comment by finnzz** [comment]
The purpose of this bridge app is to let you do voice searches with Alexa on a FireTV device. Eg. "Alexa, search youtube for cute dog clips"

For the casting function itself, you need to use the TV link option.  In SmartTubeNext, go to Settings / Linked devices / Add Device.  The app will generate a code.  Go to the YouTube app on your phone, settings and look for watch on TV, where you then enter that code.

As far as I know there is no casting feature that relies on mDNS discovery like with the stock YouTube app.

**Comment by kxd2000** [comment]
Ok, thank you. With SmartYoutubeTV app, i could cast directly, but this workaround works.

**Comment by fancellu** [comment]
The above url is broken

**Comment by finnzz** [comment]
Bridge links have been fixed
https://github.com/yuliskov/SmartTubeNext#voice-search
