### ISSUE TITLE
feature request: change font size and video thumbnail size

### ISSUE THREAD

**Issue by xPhoenisX** [yuliskov/SmartTubeNext#55]
change user interface font size, video subtitle font size and video thumbnail size

**Comment by onolox** [comment]
+1

The font of the title of videos are too big. They not fit.

**Comment by xPhoenisX** [comment]
feature has been implemented

**Comment by onolox** [comment]
I only see the option to reduce the entire UI, not only the fonts.

**Comment by falcorr** [comment]
I'd also like to be able to change the font, e.g. to something not so tall.

**Comment by onolox** [comment]
You can change 2 scales  in interface section to have the desired effect, I have the interface scale set to 0,6x and  video set to 1,2x.
