### ISSUE TITLE
Some search like "paw patrol" does not generate any result

### ISSUE THREAD

**Issue by thanghn90** [yuliskov/SmartTubeNext#566]
Hello @yuliskov !
First, thanks for this really wonderful youtube-no-ad app on android TV! Even game controller axes can navigate the app (unlike the old (stable) smart youtube tv app, which only accept DPAD_UP/DOWN/LEFT/RIGHT button signals from a remote).
However, I'm not sure if you noticed, but for some searches, such as "paw patrol" and "dora the explorer" (yes, my kid was searching, if you wonder), then there is no results after searching in smart tube next. I've tested version 10.81, 10.84, 10.75, 10.131, 10.135, and even the latest beta 10.141, on two of my TV boxes: H96 Max X2 S905X2 2GB/16GB using XTMOD AOSP rom, and TANIX TX3 S905X3 4GB/32GB using SLIMBOX 10.7 rom. The old stable Smart Youtube TV did get results with those searches, similar to the case when I use a browser on a PC to search on youtube.com. The problem is only for Smart Tube Next.
Please look into this search issue.
Thanks!

**Comment by yuliskov** [comment]
thx fire letting me know.
it's very strange since on my setup both searches working well

Regards, Yuriy

**Comment by thanghn90** [comment]
I'm currently in the US. I've tested using internet service from COX provider and on 4G data from AT&T (using my android phone). Both have the same no-search-result issue with "paw patrol" and "dora the explorer". I've tried logging in to my youtube account, as well as searching before logging in. No luck. I'll ask my sister in my home country to test it with my home country's network. It is possible that the issue might be related to regional restriction, because paw patrol and dora the explorer seems to be copyrighted series on other platform in the US (Amazon videos / netflix / etc...). However, please keep in mind that the old stable Smart Youtube TV is working with those searches, and I can play them without issue, so it may not be entirely regional restriction problem...
Is there any search API differences between the old stable Smart Youtube TV and Smart Tube Next?

**Comment by thanghn90** [comment]
Ok my sister confirms that she did get some search result for "paw patrol" back in my home country. So this is clearly something related to regional restriction. Yet, what strikes me is that the old stable Smart Youtube TV app works, while Smart Tube Next does not.
For now, I will need to live with the good old Smart Youtube TV app. Please let me know if you find out anything related to regional settings of the search function for Smart Tube Next. Maybe add an option for users to change the region for Smart Tube Next, if possible?

**Comment by thanghn90** [comment]
Well, suddenly today those searches (e.g. "paw patrol") work. I have no idea why. Probably have to thank (or blame) google. Still, just in case someone comes across a similar search issue with smart tube next, try the good old smart youtube tv stable app!
