### ISSUE TITLE
"Recommended" category is now missing from Home menu

### ISSUE THREAD

**Issue by costinmx** [yuliskov/SmartTubeNext#572]
Hi, 
Just a short note to developers:
Looks like due to very recent changes in YouTube's Home structure, "Recommended" category dissapeared from SmartTube Next Home menu. However, it shows fine in old SmartYoutube, or in original app...
Regards

**Comment by foreveryoungforty** [comment]
Strange , I still have Recoommended in the Home, even as the first category on top. Maybe a regional related issue (I am in Belgium).

**Comment by costinmx** [comment]
I have Reccomended in Home, in old Smart Youtube and in original app. Just as usual. It also shows in Android Home menu with the SmartTube Next channel... It does not look as a regional issue by Youtube, unless it s a SmartTube regional issue... My youtube settings are Language: English US, Location: Romania, SmartTube Language:Default. Regional Android setting point to UK.
Category is missing for at least 3 days.... Tried a lot of workarounds, including clear cache, restart, etc. No "recommended" anymore

**Comment by costinmx** [comment]
"It also shows in Android Home menu with the SmartTube Next channel... "

A closer look shows I was wrong about that,  STNext Android Home Channel now shows Recommended entries from Music category, not from Home, as it used to be.

**Comment by costinmx** [comment]
Now it is clear. Actually, is quite simple: SmartTubeNext completley miss the first (newly introduced) Youtube tab/header "For You: Recommended", and it shows from the next one below, whatever it is....

**Comment by costinmx** [comment]
Everything went back to normal yesterday, right after Youtube pulled out their new "For You" tabbed section. 
"Recommended" shows up again, top of the list in Home menu in SmartTube Next. Same goes for Android Home, "Recommended" works normal again with STNext home channel. 

I wonder why they ditched the new tabbed section. And if it's going to be back at some point. 
"Browse by topic" section, still there.
