### ISSUE TITLE
Can’t download the video - v11.3

### ISSUE THREAD

**Issue by tomiteko** [yuliskov/SmartTubeNext#600]
I’m getting error message “Can’t download the video” for every video when trying to play it after update to 11.3.

Device: Xiaomi Mi TV Stick, Android TV 9

**Comment by kubawolanin** [comment]
Have you resolved the issue @tomiteko?

**Comment by tomiteko** [comment]
It just started working again without any action from my side.

**Comment by rickydeez** [comment]
Getting same issue here, on shield.
