### ISSUE TITLE
Videos are not playing with error message "Can't download video"

### ISSUE THREAD

**Issue by iamdegenerat3** [yuliskov/SmartTubeNext#612]
Error description: Initial playback on multiple (~30-50%) videos fails with 'Can't download video'. If I go back and start again nearly all videos will load properly. The videos that won't start work fine with OG YouTube app and SmartYoutube app

Setup:
Nvidia Shield P2897 (2016 version)
Android TV 9 (patch level Dec 5, 2020, Kernel 4.9.140-tegra)
Shield SW Version 8.2.2
SmartTubeNext Version 11.6

Network Setup:
1gbit WAN connection
LAN is wired with 2x TP-Link Gbit switches

I'm working in testing for Vodafone and have further knowledge in network analyzing. Just hit me up if you need further analysis or some testing done.

**Comment by kriztan** [comment]
I can confirm the problem. But it behaves a bit different. I'm using the current app version on a nvidia shield 2015. I can't play any videos as long as I'm logged in with the error message @iamdegenerat3 mentioned. The playback starts working instantly if I would log out.

**Comment by iamdegenerat3** [comment]
That's quite interesting. Just tested different video player settings to see if that changes anything which it didn't.
Will see if your 'workaround' works for me as well so maybe the devs can have a closer look at it

**Comment by iamdegenerat3** [comment]
Since one of the last updates my issue has more or less disappeared. Thanks and cheers to the dev! :)

**Comment by eddie303** [comment]
This issue appeared abbout a week ago and it persists on both a Mi Box S and a Mi smart Projector.
