### ISSUE TITLE
Videos randomly stop playing after v11.3

### ISSUE THREAD

**Issue by ManuLinares** [yuliskov/SmartTubeNext#614]
For a week now, on v11.6, still. Videos randomly stop playing.

I have to reopen the video and playback starts, but again randomly it stops playing, some after 15min, some after 45min, some a few minutes in. It goes back to previous screen so I open the video again and "luckily" it saves the time and it starts of from when it stopped.

*System*
Firestick gen1

edit: I saw the *very unstable release* in changelog

**Comment by foreveryoungforty** [comment]
Update 11.8 should fix it

**Comment by ManuLinares** [comment]
Been using 11.8 for 3 days now, still randomly closing. Very annoying for live shows as I lose a few seconds and cannot rewind.

**Comment by ManuLinares** [comment]
Could not reproduce yesterday, closing

**Comment by zhaoguomanong** [comment]
stil reproduced on 16.60, playback randomly stopped and back to home video list.
