### ISSUE TITLE
History not updating any more in 11.8

### ISSUE THREAD

**Issue by Lichtblitz** [yuliskov/SmartTubeNext#621]
In a setup with two accounts, history is not updating any more since the update to 11.8. The previous version was 11.5 or something like that.
The problem exists for both accounts.

Restarts of the app and the whole system did not help. Before the update it worked fine.

**Comment by foreveryoungforty** [comment]
Indeed, also problem over here with the history... does not update since yesterday.

**Comment by foreveryoungforty** [comment]
solved in 11.17-update.

**Comment by Lichtblitz** [comment]
I can verify the issue is fixed in the new version, thanks 😊

**Comment by Lichtblitz** [comment]
There's been a regression. History stopped working in 11.27 again.

**Comment by Lichtblitz** [comment]
Fixed in 11.28 again
