### ISSUE TITLE
11.27 Crashes Firestick Installer 

### ISSUE THREAD

**Issue by ACR-Jeff** [yuliskov/SmartTubeNext#641]
I have been using SmartTubeNext since the beginning and never have encountered any issue until now. Suddenly I started SmartTubeNext on my Firestick 4k and got a notification from the app that there was an update for SmartTubeNext Version 11.27. I clicked the "Install Update" from there is when the installer menu pops up and then suddenly crashes. I have installed other Apps on my Firestick to make sure it wasn't the Firestick itself and to diagnose the issue. Yet SmartTubeNext is the only App this happens with. If in need of anymore information please let me know. Thanks for your hard work and great application.
Specs are as follows:
Fire OS 6.2.7.3
Fire TV Home Version: 6240042.1
SmartTubeNext Installed version: 11.22
SmartTubeNext Settings: SponsorBlock Enabled
Process Taken to Update: Always use the Apps Update Notification and Install directly from the App.

**Comment by devprjgithub** [comment]
Exact same issue on BRAVIA 2015 Sony Android TV. Cannot  update 11.22 to 11.27 by using in-app update. On first dialog just exit/crash without any messages.

**Comment by TScheen** [comment]
Exact same behavior on my Phillips Android TV.

**Comment by costinmx** [comment]
Same issue with Bravia 2019 Android TV. In-app update crashes install with 11.27 (never happened before)

**Comment by Rathna-K** [comment]
Same issue on Fire TV Cube. Will it be fixed or do we have to manually download and install? And thank you for the awesome app!

**Comment by sokai** [comment]
11.28 is installing fine (again) 🥳

**Comment by TScheen** [comment]
11.28 installed today without crashes.

**Comment by ACR-Jeff** [comment]
Still not installing on Firestick 4K. Exactly the same issue in my OP occures.

**Comment by costinmx** [comment]
11.28 installed fine on ATV, too

**Comment by Rathna-K** [comment]
Still same issue in the fire tv cube though with 11.28

**Comment by Rathna-K** [comment]
> 11.28 is installing fine (again) 🥳 #closed

Could you please open this or should we open another issue? Thank you

**Comment by ACR-Jeff** [comment]
> > 11.28 is installing fine (again) partying_face #closed
> 
> Could you please open this or should we open another issue? Thank you

This hasn't been closed @sokai is closing his issue. I hope the Developers address this issue soon. Yet my SmartTubeNext is working fine still on version: 11.22.

**Comment by ACR-Jeff** [comment]
Well since it appears this issue isn't going to be resolved. I also tried to update through the app to version 11.33 still crashed. I resorted to installing directly from the version 11.33 apk. If this happens again I will open another issue.
