### ISSUE TITLE
Stopped logging watched videos in history 

### ISSUE THREAD

**Issue by joaocbsilva** [yuliskov/SmartTubeNext#656]
SmartTubeNext app v 11.27 in MiBox, no longer  able to log watched videos in History. 
Using YouTube app, works perfectly.

**Comment by Grauen** [comment]
Same here. Version 11.28

**Comment by Nano0k** [comment]
11.28 update fixed it for me. Watched a new vid on Fire Stick and it showed in my watch history on PC.

Thanks yuliskov!

**Comment by joaocbsilva** [comment]
Version 11.28 fixed it. Thanks! Awesome job.

**Comment by albino1** [comment]
For me history was fixed in 11.28, but it's broken again in 11.33 on both my Shield and my Fire TV.  Anybody else?
