### ISSUE TITLE
black screen when playing video

### ISSUE THREAD

**Issue by pakyrs** [yuliskov/SmartTubeNext#677]
Hi there,

The app has been working flawlessly for very long, today after watching a video the player went black with just the title showing. I played with the settings and doesn't seem to get back to normal.

any way to solve this?

Thanks

**Comment by Muegic** [comment]
Same here. Had this issue before and restarting my Shield TV always solved the problem. But not today.

**Comment by phil2sat** [comment]
Same here

**Comment by Guruputra** [comment]
Same here, is this worldwide issue?

**Comment by KeKyKo** [comment]
Starting about 2 hours ago no videos will play.  I can select a video but it will not play.  Also backspace does not work.  I need to press backspace 3 times to get back to the main menu.  Thanks.

**Comment by hamswolo** [comment]
Same on Fire tv , been getting endless buffering when what I'm assuming is an ad trying to load for about 3 days now it goes black.

**Comment by rodalpho** [comment]
Indeed, completely broken now. Yuli is in Russia I think so he's probably sleeping.

**Comment by felipedraco** [comment]
aqui também ta off não reproduz

**Comment by finnzz** [comment]
There was a YouTube API change:
https://github.com/yuliskov/SmartTubeNext/issues/676#issuecomment-863601777

**Comment by Djtiestoja** [comment]
Same issue here

**Comment by echo950** [comment]
Same problem here. But, YouTube Vanced  still works in my phone.

**Comment by finnzz** [comment]
SmartTubeNext v11.37 was pushed out with a fix, and videos are loading again

**Comment by pakyrs** [comment]
can confirm the new version works.

**Comment by KeKyKo** [comment]
HOORAY!  ITS WORKING.  Thank you Yuliskov :)

**Comment by adammyesthatsme** [comment]
Where can find this working version?

> can confirm the new version works.

Where can i find this working version?

**Comment by adammyesthatsme** [comment]
> HOORAY! ITS WORKING. Thank you Yuliskov :)

I’m new to github could you direct me to the working link please :)

**Comment by KeKyKo** [comment]
I didnt go to his link I just went to : Settings-about-check for updates.  Waited for 20 seconds and it showed me that there was an update to 11.37.  I clicked to install the update.

**Comment by adammyesthatsme** [comment]
> I didnt go to his link I just went to : Settings-about-check for updates. Waited for 20 seconds and it showed me that there was an update to 11.37. I clicked to install the update.
> BUT if you want to install from the beginning: https://github.com/yuliskov/SmartTubeNext Click "Download ZIP

still not working but I appreciate the help mate

**Comment by KenMerritt** [comment]
> 
> 
> > I didnt go to his link I just went to : Settings-about-check for updates. Waited for 20 seconds and it showed me that there was an update to 11.37. I clicked to install the update.
> > BUT if you want to install from the beginning: https://github.com/yuliskov/SmartTubeNext Click "Download ZIP
> 
> still not working but I appreciate the help mate

Keep in mind it will not work depending on what you're using to download. For example on FireTV if you use Firefox it will not work the Firestick blocks the download. You have to use a downloader app. On the Firestick I use Downloader by AFTVnews

**Comment by adammyesthatsme** [comment]
> > > I didnt go to his link I just went to : Settings-about-check for updates. Waited for 20 seconds and it showed me that there was an update to 11.37. I clicked to install the update.
> > > BUT if you want to install from the beginning: https://github.com/yuliskov/SmartTubeNext Click "Download ZIP
> > 
> > 
> > still not working but I appreciate the help mate
> 
> Keep in mind it will not work depending on what you're using to download. For example on FireTV if you use Firefox it will not work the Firestick blocks the download. You have to use a downloader app. On the Firestick I use Downloader by AFTVnews

I really appreciate the help but I am using downloaded on my FS and tried doing what you said I think some devices it’s still not working 👍
