### ISSUE TITLE
Can't download the video.

### ISSUE THREAD

**Issue by DhruvSagar07** [yuliskov/SmartTubeNext#684]
it shows can't download the video. It try to refresh again but again the it shows can't download video.

**Comment by igetboredthinkingofusernames** [comment]
Same issue here after recent update.
Anyway to roll back?

**Comment by erkange** [comment]
Same here, for some videos especially music videos

**Comment by USvsTHEM** [comment]
wtf did you guys do we dnt wanna download the videos we jud wanna play em come on mannn

**Comment by Ketec** [comment]
Everything that qualifies as a "music video" fails to download.

Take something like 10-second songs  - covers/parodies. No longer play at all.

**Comment by hamswolo** [comment]
I'm having the music issue as well ,it seems to be specific to videos with a bands name in it. I can listen to mixes and live music seems to work too.

**Comment by igetboredthinkingofusernames** [comment]
The new update has fised the issue!
Many thanks for your help.

**Comment by buthig666** [comment]
same on 2020 Sony Bravia not fixed with 11.40

**Comment by kishorer747** [comment]
Its fixed now. I can watch music videos on version 11.60
