### ISSUE TITLE
Same issue , different person 

### ISSUE THREAD

**Issue by adammyesthatsme** [yuliskov/SmartTubeNext#685]
app not working as we all already know if you find solution please put it here or not 👍

**Comment by E-D-W-I-N** [comment]
@adammyesthatsme Are you logged in your Google account?

**Comment by adammyesthatsme** [comment]
> @adammyesthatsme Are you logged in your Google account?

I was the first time but when I reinstalled the new version I wasn’t do you think that will make a difference?

**Comment by gusfon83** [comment]
11.37 isn't working for me too. Using on a mi box S (Android 9) and on a Mecool KD1 (Android 10).

**Comment by costinmx** [comment]
OMG ... Why are you opening a new issue when there are at least 5 similar ? #680 #681 #684 etc...

**Comment by erkange** [comment]
Same for me. Can't download video error

**Comment by adammyesthatsme** [comment]
> OMG ... Why are you opening a new issue when there are at least 5 similar ? #680 #681 #684 etc...

Right well one I’m new to this and two I asked if any one finds a solution put it on here whereas others are just saying it’s not working so quite being a prick on GitHub 😐

**Comment by adammyesthatsme** [comment]
> > OMG ... Why are you opening a new issue when there are at least 5 similar ? #680 #681 #684 etc...
> 
> Right well one I’m new to this and two I asked if any one finds a solution put it on here whereas others are just saying it’s not working so quite being a prick on GitHub 😐

Quit

**Comment by adammyesthatsme** [comment]
> OMG ... Why are you opening a new issue when there are at least 5 similar ? #680 #681 #684 etc...

Yes you’re right Ngl I’m new to this so I’m still not sure on stuff but yeah the creator shouldn’t have to be bombarded with issues and issues so I’ve closed mine.

**Comment by kishorer747** [comment]
Its fixed now. I can watch music videos on version 11.60
