### ISSUE TITLE
Impport project and build is not successful( SharedModules\core_settings.gradle' as it does not exist).

### ISSUE THREAD

**Issue by lanphuongkhtn** [yuliskov/SmartTubeNext#693]
![z2565482932476_71a4ee1a60ea4b919e0cb3c28a0bfd5d](https://user-images.githubusercontent.com/79295436/122703975-e2eea380-d27c-11eb-9d05-e4a8bdf3e2eb.jpg)
I try to import project SmarttubeNext and run:
Result: Error
"Caused by: org.gradle.api.resources.MissingResourceException: Could not read script 'D:\ANDROID\SmartTubeNext-master\SharedModules\core_settings.gradle' as it does not exist"
**SharedModules\core_settings.gradle' as it does not exist**
Can you help me fix this problem?
Thanks

**Comment by nguoianphu** [comment]
Not sure how did you closed it but I think you missed a step before building.
`git submodule update --init`
