### ISSUE TITLE
Slow load with good internet. Videos stop

### ISSUE THREAD

**Issue by radiomaniac** [yuliskov/SmartTubeNext#700]
Hi, I've been having issues lately, can't watch videos in 1080p, it just can't load properly and sometimes videos in 720p get stuck again and again.

I don't have issues when playing 1080p videos on other apps like Disney plus for example. Is there anything I can do to fix this? Or is it a bug?

**Comment by NGGiovanni** [comment]
I'm also having a issue similar to this one, I watch some videos and then the video starts to buffer at every second. Only goes away restarting the device, also tried cleaning cache, but nothing helped.

**Comment by webfabioBR** [comment]
same problem, this bug is so sad, i cant run some random videos, i need change to 240p... but my internet isnt the problem, if i choice others video i dont have problem. ill try this new 11.42 now or any older version.

**Comment by BenLH77** [comment]
Same here. Kept thinking it was my internet.

**Comment by todoesUno** [comment]
I had the same problem with my Fire TV Stick, the video started to buffer every second. So I installed the "Crosswalk project runtime" library, and now the video works fine, no breaks.

**Comment by radiomaniac** [comment]
> I had the same problem with my Fire TV Stick, the video started to buffer every second. So I installed the "Crosswalk project runtime" library, and now the video works fine, no breaks.

Interesting, I tried to install that into my Android tv but it didn't let me. It said "unknown application" . Tried a couple of apk's but I couldn't install any of them.

**Comment by tj200** [comment]
I'm facing the same issues lately, some videos buffer every few seconds. Some videos don't even start to play ("can't load video ...."), loading several times the video or watch an other video first, it may work. 

The constant buffering is really crazy, you can't watch any video properly! (1080p on FireStick TV 4k) My internet is good and stable on every other app or PC.

**Comment by webfabioBR** [comment]
> I had the same problem with my Fire TV Stick, the video started to buffer every second. So I installed the "Crosswalk project runtime" library, and now the video works fine, no breaks.

i tried this apk but still have bug. ill try now older version next beta like 3-4 months later...
anyone know where i find it?

**Comment by Grauen** [comment]
https://github.com/yuliskov/SmartTubeNext/issues/658

**Comment by radiomaniac** [comment]
Alright the issue is not fixed but looks like I didn't search enough and this is an already opened issue, number #658 as referenced by user "Grauen" , so I'm closing this one
