### ISSUE TITLE
[Feature request] browse through video comments 

### ISSUE THREAD

**Issue by JRLS** [yuliskov/SmartTubeNext#706]
This app is awesome!!!!
I also love the frequent updates, which makes the app even better :)

request : is it possible to add the ability to browse through the video comments?
that would be great :)

if it's already in there i missed it... but i couldnt find it..

**Comment by Vistaus** [comment]
I too am longing for this feature! The new live chat option is nice, but I much, much rather have integrated comments! Even if read-only (I never write comments from my TV anyway).

**Comment by C-O-D** [comment]
I'd also absolutely appreciate the ability to at least being able to read the comments section since it's somehow essential and would make this app much more useable and even more stellar.

**Comment by BobbyWibowo** [comment]
Eiyyo, latest beta build has a button to view comments on the player view now
Currently fixed to sorting by top comments only, but hey, I think it was only added within the recent few days, so big progress already 🎉

**Comment by JRLS** [comment]
just tested the new version
with comments now!
EXCELLENT! Thanks! :)

**Comment by JRLS** [comment]
thanks!
