### ISSUE TITLE
Smarttubenext gets automatically deleted in recent Chinese MiTV os

### ISSUE THREAD

**Issue by ibin7777** [yuliskov/SmartTubeNext#724]
In the recent MiTV firmware update, it started deleting some of the apps like netflix and youtube
My guess is it's because smarttubenext has similar package name to the official Youtube app, but I'm not sure.

**Comment by lokpro** [comment]
Maybe a duplicate of https://github.com/yuliskov/SmartTubeNext/issues/592

**Comment by ibin7777** [comment]
> Maybe a duplicate of #592

Yes it is, and resetting did solve the problem, thank you.
