### ISSUE TITLE
Feature Request: Turn off auto-skipping segments

### ISSUE THREAD

**Issue by JoeGeC** [yuliskov/SmartTubeNext#744]
Version: 11.57

Issue: automatically skips segments of videos such as intros and promotions, even when the user has not requested this to happen

Request: allow the user to turn this feature off

**Comment by kishorer747** [comment]
> Version: 11.57
> 
> Issue: automatically skips segments of videos such as intros and promotions, even when the user has not requested this to happen
> 
> Request: allow the user to turn this feature off

Did you try turning off in Settings under SponsorBlock? There is an option to un-select various options like "Intro promotion", "Non-music section", etc..
