### ISSUE TITLE
Getting "Can't download the video" error on random videos or playlists

### ISSUE THREAD

**Issue by Playfrog4u** [yuliskov/SmartTubeNext#751]
I'm using the beta and was working great but now none of the music videos I'm trying to play works or some random videos. Then some videos work, but never the same one that don't work.
I have uninstalled, and reinstalled but still no luck. Just strange I was able to share from phone then same video won't load.

Thanks!

**Comment by Playfrog4u** [comment]
Noticed this was already an issue, I'll go ahead and close this issue

**Comment by Bobby1000** [comment]
Same. Many music videos fail with "cannot download the video" error. Some now generate a debug error which, in some cases, causes the app to go into an endless loop. The videos that are now failing worked previously in this release on SmartTubeNext, so it would seem these errors may be due to recent changes made on youtube.

**Comment by kishorer747** [comment]
> Same. Many music videos fail with "cannot download the video" error. Some now generate a debug error which, in some cases, causes the app to go into an endless loop. The videos that are now failing worked previously in this release on SmartTubeNext, so it would seem these errors may be due to recent changes made on youtube.

I am facing the same issues too. Same music videos were playing few days ago. Its not working now in latest versions. Tried in both stable/beta versions and not working in both cases.

**Comment by kishorer747** [comment]
Its fixed now. I can watch music videos on version 11.60

**Comment by stodd3** [comment]
> Its fixed now. I can watch music videos on version 11.60

11.60 worked right after updating, but now the problem is occurring again.

**Comment by Wicked0ne** [comment]
I'm getting the same thing with 11.60 on a firetv stick 4k.

I'm not sure if it's related, but on videos that do play, I get a debug toast message saying its dumping debug info a folder. This message only appears on some videos that play

**Comment by kishorer747** [comment]
Not sure what the issues are with debug toast messages, even I am seeing for some videos. But able to play most of the videos, so all good for now.

I turned off auto-update after updating to 11.60.
