### ISSUE TITLE
Many videos won’t play, says “cannot download video”.

### ISSUE THREAD

**Issue by Sparcrypt** [yuliskov/SmartTubeNext#778]
Has been happening for last several updates. Briefly working immediately after updating to 11.74 but now won’t work again.

Tried on Shield Pro and a Sony android TV.

**Comment by ashleysommer** [comment]
Same. App has been working great for the last week, now almost all videos say "can't download the video".

**Comment by rumagent** [comment]
I have the same issue (currently on 11.91, but the issue has persisted for a while). Using a Nvidia Shield TV. 

Curiously enough, if i press and to the menu and hit the "play" icon, it will play just fine.

**Comment by ashleysommer** [comment]
My issue seemed to resolve itself, about a week after posting my comment above. What it started working was not related to a software version update, I think the problem lies elsewhere.

**Comment by kkwangchaoyi** [comment]
I have the same issue (currently on last 
xiaomi tv 6
