### ISSUE TITLE
Search not showing any results. 

### ISSUE THREAD

**Issue by ashayer** [yuliskov/SmartTubeNext#844]
There are no search results popping up regardless of search.

**Comment by lokpro** [comment]
me too

**Comment by Shasdo** [comment]
Same for me on Shield TV
App and Shield both up to date.

The search interface is present but the background is black, whatever you search for.

**Comment by rmrten** [comment]
Same issue here. No search results.

Device: Sony X90H
App version: 11.47
OS: Android TV 9 
Kernel: 4.9.125

**Comment by lokpro** [comment]
I have updated to latest and it is working again. Thanks the developer.

**Comment by rmrten** [comment]
Downloaded latest stable and working again. Check update on previous was also broken, didn relize that. Thanks
