### ISSUE TITLE
Playlists - slow loading on the sidebar

### ISSUE THREAD

**Issue by costinmx** [yuliskov/SmartTubeNext#846]
Hi,
Since last week updates, it takes at least 8-10 seconds to load a playlist on the sidebar. 
Also, Playlists section load is quite sluggish now (I always used Row style, and it was always fast)

P.S. At some point this summer the app was pretty perfect. Sorry to see that we are back in Beta phase. It feels like it, again.

**Comment by costinmx** [comment]
After 30/31 August updates, loading time for sidebar pinned playlists increased even more to 15 seconds minimum. Sometimes returns "can't load". This basically renders sidebar pinning useless.

**Comment by Rin-Rem** [comment]
Oh it's gotten worse... as of sep 3rd mine won't even load anything including user code to sign back in. Idk what happened. Didn't update it recently, so idk what could of changed so suddenly.

**Comment by angielskim** [comment]
The problem still occurs in version 13.30 (mi box s global).  Please fix this.

**Comment by yuliskov** [comment]
Loading pinned playlists has always been slow, guys. There is no regression. However, I agree that this needs some optimization.

**Comment by costinmx** [comment]
All issuses solved in v13.66. More elements are working way faster now, not just suggestions. 
Great job, Yuri. Thanks for your dedication to this project. 

Hope there will be a fix soon also for #1094 #1083. This may result in a major stable release :)
