### ISSUE TITLE
[Feature Request] Block/mute/hide channels

### ISSUE THREAD

**Issue by ForestWolf91** [yuliskov/SmartTubeNext#856]
Hey I really appreciate your work, glad I found it before lost my mind trying to use official YouTube for Android TV. 
Anyway, if possible have a way to Block/mute/hide channels from showing up. For example MrBeast. Several times I click not interested but it still appears in my feeds/suggestions. I blow at coding so can't help 😬 
But would appreciate if could find a way for this to happen. 

Thanks *Howl* 🐺

**Comment by rashnk** [comment]
Why is issue closed, there is no such option available

**Comment by ForestWolf91** [comment]
> Why is issue closed, there is no such option available

True not a way to hide/block channels. But on suggested videos if you press and hold and select not interested. Then the channel you don't like won't be recommended. 

Also delete any history of watching any of that channel videos. That will help. 

Nore: I haven't used app in a while so it may have changed.
