### ISSUE TITLE
Issue with back to back SponsorBlock Categories

### ISSUE THREAD

**Issue by cobhc2019** [yuliskov/SmartTubeNext#864]
I've noticed that if a video has two different categories back to back that the app will now only skip the first one it comes to and not both.

https://youtu.be/8NK1I6S_vFs

On this video for example it will skip the Sponsor but not the Intro. And if I cue the video back to a spot during the Sponsor, it will then skip the intro but it will never do both.

This has been happening for some time now but I'm sorry, I didn't take note of when this bug first appeared. I'm on the latest beta on an Nvidia Shield TV.

Thanks.

**Comment by cobhc2019** [comment]
Strangely though it works fine on this video

https://youtu.be/-34tu7uXCI8

**Comment by ezvr** [comment]
I have also noticed that. Otherwise it works perfectly.

**Comment by cobhc2019** [comment]
Fixed in
