### ISSUE TITLE
SmartTubeNext doesn't have connection

### ISSUE THREAD

**Issue by rusefendi** [yuliskov/SmartTubeNext#897]
On version 12.53 all worked fine, but eventually lost connection to internet. I am using Xiaomi Android tv. Standard YouTube app working good. I tried clean cache and all settings, but it doesn't help. Also tried logout and login, but it doesn't show authorization code

**Comment by Alex01d** [comment]
Today I've faced the same in Russia. NewPipe doesn't work neither. Looks like a government TLS filter.

Related forum thread: https://ntc.party/t/tls-youtube/1311/15
