### ISSUE TITLE
Feature request: Themes 

### ISSUE THREAD

**Issue by kiarfuzzy** [yuliskov/SmartTubeNext#93]
App works really nice, only thing that is missing are some themes, that blue greenish color looks not so great. Maybe some dark / gray theme would look way better.

**Comment by kiarfuzzy** [comment]
I used a apk editor to change the colors myself, just too see how it would look. Here are some screenshots:

https://i.imgur.com/EC5Rvwt.png
https://i.imgur.com/BrvrqOU.png

It looks pretty dope now :D, please make something like this as default (i took the color codes from youtube website)

**Comment by adarshvadwitiya** [comment]
+1

**Comment by raddacle** [comment]
+1

**Comment by gate1975mlm** [comment]
+1
