### ISSUE TITLE
After logging in, no choice to select YouTube brand Account.

### ISSUE THREAD

**Issue by Shinobyte** [yuliskov/SmartTubeNext#943]
Ive been using YouTube since the beginning and thus my account has been designated as a "brand account" . When logging in to SmartTubeNext I can not select an account so sadly it logs on to the non brand account, which I dont use.

**Comment by Shinobyte** [comment]
Seems to work. Got a choice to select out of my two accounts

**Comment by HerrFrosch5** [comment]
Does not work for me, either. Neither with beta nor with stable version.
