### ISSUE TITLE
[Feature Request] filter channel by upload date (oldest), Most popular, Upload date (newest)

### ISSUE THREAD

**Issue by Loading617** [yuliskov/SmartTubeNext#958]
I wanna be able to filter channels so i don't have to scroll right or left so can y'all plz add this feature

**Comment by bradMatias** [comment]
If you long press on a channel in the channels menu it will bring up an option to open channel.  This allows you to see uploads by newest, uploads sorted by highest view count, created playlists and a bit more.  I don't think there is currently a way to sort by oldest -> newest though.
