### ISSUE TITLE
60fps playback not working unless video controls are onscreen.

### ISSUE THREAD

**Issue by phn08** [yuliskov/SmartTubeNext#962]
Exactly as the title says, video does not play at 50/60fps unless the video controls are onscreen, and will play at half the framerate (25/30fps).
30fps videos play fine.
I have tried changing the resolution of the video between 1080p and 720p, and tried changing between AVC and VP9, none of this has helped.
Enabling "Ambilight fix" in the "Developer options" menu seems to allow the video to play at 60fps without the video controls being onscreen, but with a cost to image quality..

**Comment by Reverend-K** [comment]
I'm having a similar problem, only the problem persists regardless of video controls being onscreen or not.  Random framerate drops and stuttering are present at all 1080/60 settings.  720p works better, but not perfectly.  I'm not sure what "auto frame rate" does but it doesn't fix the problem.  
I've also tried the fixes in the developer options and adjusting buffer size to no avail. 
I was previously using Smart Youtube TV without any framerate issues.  
1080/24 content plays fine so I think this is a 60fps issue.  
Device is an Amazon Fire TV.

**Comment by phn08** [comment]
Issue still persists on the latest beta (13.39), still requiring Ambilight Fix to be enabled for video to playback at 60fps.

**Comment by phn08** [comment]
Issue is now fully resolved by using "Tunneled video playback". Closing.
